// Resolved for workspace monorepo
include ':capacitor-android'
def capAndroidDir = new File('../node_modules/@capacitor/android/capacitor')
if (!capAndroidDir.exists()) {
  capAndroidDir = new File('../../customer-app/node_modules/@capacitor/android/capacitor')
}
project(':capacitor-android').projectDir = capAndroidDir
