import { HomepageLayoutConfig, HomepageSectionConfig } from '@/types/homepageCms';

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSectionConfig[] = [
  {
    id: 'sec-hero-main',
    type: 'Hero',
    title: 'Groceries delivered in 10 minutes',
    subtitle: 'Fresh farm produce, pantry essentials, dairy & festive treats at everyday low prices',
    badge: '⚡ LIGHTNING FAST',
    ctaText: 'SHOP NOW',
    ctaLink: '/categories',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    layoutStyle: 'banner',
    displayOrder: 1,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-shop-by-category',
    type: 'ShopByCategory',
    title: 'Shop By Category',
    subtitle: 'Explore 2000+ items across daily staples',
    layoutStyle: 'grid',
    displayOrder: 2,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-buy-again',
    type: 'BuyAgain',
    title: '🛒 Buy Again',
    subtitle: 'Quick 1-tap reorder for your regular daily essentials',
    badge: 'INSTANT REORDER',
    layoutStyle: 'carousel',
    maxItems: 8,
    displayOrder: 3,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-flash-sale',
    type: 'FlashSale',
    title: '🔥 Today’s Flash Deals',
    subtitle: 'Limited stock discounts up to 50% OFF',
    badge: 'LIMITED TIME',
    layoutStyle: 'carousel',
    maxItems: 8,
    displayOrder: 4,
    targetPersona: 'ALL',
    targetDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    showTimer: true,
    isActive: true,
  },
  {
    id: 'sec-frequently-bought',
    type: 'FrequentlyBoughtTogether',
    title: '✨ Frequently Bought Together',
    subtitle: 'Save extra 10% on curated 3-item value bundles',
    badge: 'EXTRA 10% OFF',
    layoutStyle: 'compact',
    targetProductIds: ['p-bread-1', 'p-butter-1', 'p-jam-1'],
    displayOrder: 5,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-recommended-for-you',
    type: 'RecommendedForYou',
    title: '❤️ Recommended For You',
    subtitle: 'Curated picks tailored to your shopping preferences',
    badge: 'PERSONALIZED',
    layoutStyle: 'carousel',
    maxItems: 8,
    displayOrder: 6,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-free-gift',
    type: 'FreeGift',
    title: '🎁 Free Gift on Orders Above ₹500',
    subtitle: 'Add ₹500+ groceries to unlock a free surprise reward',
    badge: 'FREE GIFT',
    thresholdAmount: 500,
    ctaText: 'SHOP ESSENTIALS',
    ctaLink: '/categories',
    layoutStyle: 'banner',
    displayOrder: 7,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-because-you-bought',
    type: 'BecauseYouBought',
    title: '🍲 Because You Bought Daily Staples',
    subtitle: 'Complementary items you might need for cooking',
    layoutStyle: 'carousel',
    maxItems: 8,
    displayOrder: 8,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-popular-products',
    type: 'PopularProducts',
    title: '⭐ Bestsellers & Top Rated',
    subtitle: 'Most loved products by thousands of happy neighbors',
    badge: 'TOP RATED',
    layoutStyle: 'carousel',
    maxItems: 10,
    displayOrder: 9,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-loyalty-progress',
    type: 'LoyaltyProgress',
    title: '⭐ PocketKirana Rewards Club',
    subtitle: 'Complete 5 orders to unlock ₹50 OFF + Free Delivery on every milestone order',
    badge: 'MILESTONE REWARD',
    layoutStyle: 'compact',
    displayOrder: 10,
    targetPersona: 'ALL',
    isActive: true,
  },
  {
    id: 'sec-brand-collections',
    type: 'BrandCollections',
    title: 'Featured Trusted Brands',
    subtitle: 'Direct from Amul, Tata Sampann, Fortune, Aashirvaad & Mother Dairy',
    layoutStyle: 'grid',
    displayOrder: 11,
    targetPersona: 'ALL',
    isActive: true,
  },
];

export const DEFAULT_HOMEPAGE_LAYOUT: HomepageLayoutConfig = {
  id: 'layout-default-master',
  name: 'Default Master Homepage',
  description: 'Standard quick-commerce dynamic homepage layout with personalization, bundles, and instant reorders.',
  version: 1,
  status: 'PUBLISHED',
  sections: DEFAULT_HOMEPAGE_SECTIONS,
  publishedAt: '2026-08-01T00:00:00.000Z',
  createdAt: '2026-08-01T00:00:00.000Z',
  updatedAt: '2026-08-01T00:00:00.000Z',
  createdBy: 'PocketKirana Admin',
};
