import { FestivalTemplate } from '@/types/festival';

export const INITIAL_FESTIVAL_TEMPLATES: FestivalTemplate[] = [
  // ── TEMPLATE 01: GANESH CHATURTHI ──
  {
    id: 'tpl-ganesh-chaturthi-premium',
    name: 'Ganesh Chaturthi Premium',
    description: 'Rich festive saffron, gold & maroon design celebrating Lord Ganesha with Modak, Puja Samagri & Festive Snacks.',
    festivalKey: 'ganesh_chaturthi',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1567591414240-e2b26056cf9e?auto=format&fit=crop&w=600&q=80',
    tags: ['Ganesh', 'Modak', 'Puja', 'Saffron', 'Festive', 'Traditional'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#EA580C', // Deep Festive Orange
      secondaryColor: '#9A3412', // Deep Ochre / Brown
      accentColor: '#FEF3C7', // Warm Cream Gold
      bgColor: '#FFFBEB',
      bgGradient: 'linear-gradient(135deg, #FFFBEB 0%, #FEF3C7 50%, #FFEDD5 100%)',
      cardBg: '#FFFFFF',
      textColor: '#7C2D12',
      accentTextColor: '#C2410C',
      badgeBg: '#F97316',
      badgeTextColor: '#FFFFFF',
      mood: 'premium_festive',
      fontStyle: 'festive_serif',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-gc-hero',
        type: 'Hero',
        title: 'Ganpati Bappa Morya!',
        subtitle: 'Celebrate with fresh handcrafted Modaks, pure Puja essentials & instant 10-minute delivery.',
        badge: 'FESTIVAL OF BLESSINGS',
        ctaText: 'EXPLORE FESTIVE STORE',
        ctaLink: '/category/sweets-snacks',
        image: 'https://images.unsplash.com/photo-1567591414240-e2b26056cf9e?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1567591414240-e2b26056cf9e?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-gc-countdown',
        type: 'Countdown',
        title: 'Ganesh Visarjan Mega Savings Ending In',
        badge: 'LIMITED TIME OFFERS',
        targetDate: '2026-09-20T23:59:59.000Z',
        active: true,
      },
      {
        id: 'sec-gc-categories',
        type: 'CategoryGrid',
        title: 'Ganesh Utsav Specials',
        subtitle: 'Handpicked grocery categories for auspicious celebrations',
        categoryIds: ['cat-sweets', 'cat-pooja', 'cat-fruits', 'cat-dairy', 'cat-snacks', 'cat-dryfruits'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-gc-modak',
        type: 'ProductCarousel',
        title: 'Modak & Sweets Haven',
        subtitle: 'Fresh Ukadiche Modak, Mawa Peda & Kaju Katli',
        badge: 'FRESH DAILY',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-gc-puja',
        type: 'Collection',
        title: 'Puja Essentials & Samagri',
        subtitle: 'Pure Ghee, Camphor, Agarbatti, Dhoop & Panchamrit',
        badge: '100% PURE',
        categoryId: 'cat-pooja',
        active: true,
      },
      {
        id: 'sec-gc-offer-banner',
        type: 'OfferBanner',
        title: 'FLAT ₹100 OFF on Puja Samagri Kit',
        subtitle: 'Use code BAPPA100 on orders above ₹499',
        tag: 'SPECIAL CODE',
        badge: 'FESTIVE DISCOUNT',
        ctaText: 'APPLY OFFER',
        ctaLink: '/category/pooja-essentials',
        image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
      {
        id: 'sec-gc-snacks',
        type: 'ProductCarousel',
        title: 'Festive Snacks & Savories',
        subtitle: 'Chakli, Chivda, Bhakarwadi & Namkeen for your guests',
        badge: 'HOSTING ESSENTIALS',
        categoryId: 'cat-snacks',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-gc-divider',
        type: 'FestivalDivider',
        title: 'Auspicious Delights For Your Home',
        active: true,
      },
      {
        id: 'sec-gc-trust',
        type: 'TrustBanner',
        title: 'Guaranteed Pure Puja Ingredients & Freshness Tested',
        badge: 'POCKET KIRANA TRUST',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 02: DIWALI ──
  {
    id: 'tpl-diwali-grand-lights',
    name: 'Diwali Grand Lights & Gifts',
    description: 'Glorious deep crimson, gold and radiant amber lighting theme for Diwali gifting, dry fruits, and sweets.',
    festivalKey: 'diwali',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=600&q=80',
    tags: ['Diwali', 'Lights', 'Dry Fruits', 'Gold', 'Gifting', 'Sweets'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#B91C1C', // Royal Crimson Red
      secondaryColor: '#7F1D1D',
      accentColor: '#FDE047', // Shimmering Gold
      bgColor: '#FEF2F2',
      bgGradient: 'linear-gradient(135deg, #450A0A 0%, #7F1D1D 50%, #991B1B 100%)',
      cardBg: '#FFFFFF',
      textColor: '#450A0A',
      accentTextColor: '#DC2626',
      badgeBg: '#EAB308',
      badgeTextColor: '#450A0A',
      mood: 'premium_festive',
      fontStyle: 'festive_serif',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-dw-hero',
        type: 'Hero',
        title: 'Grand Diwali Celebration 🪔',
        subtitle: 'Illuminate your home with premium dry fruits, gift packs, diyas & pure mawa sweets delivered in 30 mins.',
        badge: 'SHUBH DEEPAVALI',
        ctaText: 'SHOP DIWALI SPECIALS',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-dw-countdown',
        type: 'Countdown',
        title: 'Laxmi Pujan Fast Delivery Window Closing Soon',
        badge: 'EXPRESS DELIVERY',
        targetDate: '2026-11-08T20:00:00.000Z',
        active: true,
      },
      {
        id: 'sec-dw-categories',
        type: 'CategoryGrid',
        title: 'Diwali Shopping Hub',
        subtitle: 'Everything you need for Dhanteras, Choti Diwali & Laxmi Pujan',
        categoryIds: ['cat-dryfruits', 'cat-sweets', 'cat-pooja', 'cat-chocolates', 'cat-snacks', 'cat-oil'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-dw-dryfruits',
        type: 'ProductCarousel',
        title: 'Premium Dry Fruit Gift Hampers',
        subtitle: 'Cashews, Almonds, Pistachios & Walnut Gift Boxes',
        badge: 'ROYAL QUALITY',
        categoryId: 'cat-dryfruits',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-dw-offer',
        type: 'OfferBanner',
        title: 'UP TO 50% OFF ON DIWALI HAMPERS',
        subtitle: 'Bulk gifting discounts available for family and corporate gifts',
        badge: 'MEGA SALE',
        tag: 'BEST VALUE',
        ctaText: 'EXPLORE HAMPERS',
        ctaLink: '/category/dry-fruits',
        image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
      {
        id: 'sec-dw-sweets',
        type: 'ProductCarousel',
        title: 'Traditional Diwali Mithai',
        subtitle: 'Gulab Jamun, Rasgulla, Soan Papdi & Besan Ladoo',
        badge: 'PURE DESI GHEE',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-dw-puja',
        type: 'Collection',
        title: 'Laxmi-Ganesh Pujan Essentials',
        subtitle: 'Brass Diyas, Cotton Wicks, Kumkum, Chandan & Incense Sticks',
        badge: 'PUJA READY',
        categoryId: 'cat-pooja',
        active: true,
      },
      {
        id: 'sec-dw-freedelivery',
        type: 'FreeDeliveryBanner',
        title: 'Free Express Festive Delivery on all Diwali orders over ₹199',
        badge: 'ZERO DELIVERY FEE',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 03: NAVRATRI ──
  {
    id: 'tpl-navratri-vrat-special',
    name: 'Navratri Divine Vrat & Feasts',
    description: 'Vibrant orange, golden yellow and fresh floral theme designed for 9 Days of Fasting, Upwas Foods & Kanya Pujan.',
    festivalKey: 'navratri',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    tags: ['Navratri', 'Vrat', 'Fasting', 'Sabudana', 'Garba', 'Fruits'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#D97706', // Golden Amber
      secondaryColor: '#92400E',
      accentColor: '#FEF08A',
      bgColor: '#FFFBEB',
      bgGradient: 'linear-gradient(135deg, #FFFBEB 0%, #FEF3C7 50%, #FDE68A 100%)',
      cardBg: '#FFFFFF',
      textColor: '#78350F',
      accentTextColor: '#B45309',
      badgeBg: '#F59E0B',
      badgeTextColor: '#FFFFFF',
      mood: 'traditional_indian',
      fontStyle: 'clean_modern',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-nv-hero',
        type: 'Hero',
        title: '9 Divine Days of Navratri 🌸',
        subtitle: '100% Pure Vrat essentials: Sabudana, Sendha Namak, Makhana, Fresh Fruits & Singhara Atta.',
        badge: 'FASTING & FEASTING',
        ctaText: 'SHOP VRAT SPECIALS',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-nv-categories',
        type: 'CategoryGrid',
        title: 'Navratri Essentials',
        subtitle: 'Authentic fasting groceries and fresh dairy essentials',
        categoryIds: ['cat-vrat', 'cat-fruits', 'cat-dairy', 'cat-dryfruits', 'cat-pooja', 'cat-snacks'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-nv-vrat-carousel',
        type: 'ProductCarousel',
        title: 'Vrat & Upwas Essentials',
        subtitle: 'Makhana, Kuttu Atta, Sabudana, Roasted Peanuts & Rock Salt',
        badge: 'VRAT CERTIFIED',
        categoryId: 'cat-staples',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-nv-fruits',
        type: 'ProductCarousel',
        title: 'Fresh Orchard Fruits',
        subtitle: 'Apples, Bananas, Pomegranate & Papayas delivered farm fresh',
        badge: 'FARM FRESH',
        categoryId: 'cat-fruits',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-nv-offer',
        type: 'OfferBanner',
        title: 'FLAT 25% OFF ON VRAT COMBO PACKS',
        subtitle: 'Complete 9-day fasting food essentials at wholesale prices',
        badge: 'VRAT SAVINGS',
        tag: 'POPULAR COMBO',
        ctaText: 'BUY VRAT COMBO',
        ctaLink: '/category/staples',
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
      {
        id: 'sec-nv-dairy',
        type: 'Collection',
        title: 'Pure Dairy & Ghee',
        subtitle: 'Cow Ghee, Fresh Paneer, Thick Curd & Rabri',
        badge: '100% PURE',
        categoryId: 'cat-dairy',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 04: HOLI ──
  {
    id: 'tpl-holi-colors-celebration',
    name: 'Holi Colors & Flavors Fest',
    description: 'Vibrant splash palette featuring herbal colors, Thandai, Gujiya, Namkeen, and party essentials.',
    festivalKey: 'holi',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1583083527882-4bee9aba2eea?auto=format&fit=crop&w=600&q=80',
    tags: ['Holi', 'Colors', 'Gujiya', 'Thandai', 'Snacks', 'Beverages'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#DB2777', // Vibrant Festive Pink / Magenta
      secondaryColor: '#0284C7', // Sky Blue
      accentColor: '#FACC15', // Sunny Yellow
      bgColor: '#FDF2F8',
      bgGradient: 'linear-gradient(135deg, #FDF2F8 0%, #FEF08A 50%, #E0F2FE 100%)',
      cardBg: '#FFFFFF',
      textColor: '#831843',
      accentTextColor: '#DB2777',
      badgeBg: '#EC4899',
      badgeTextColor: '#FFFFFF',
      mood: 'modern_quick_commerce',
      fontStyle: 'bold_display',
      borderRadius: 'pill',
    },
    sections: [
      {
        id: 'sec-hl-hero',
        type: 'Hero',
        title: 'Rang Barse! Happy Holi 🎨',
        subtitle: '100% Herbal Gulal, Kesariya Thandai, Mawa Gujiya & Refreshing Drinks delivered in minutes.',
        badge: 'FESTIVAL OF COLORS',
        ctaText: 'GET HOLI READY',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1583083527882-4bee9aba2eea?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1583083527882-4bee9aba2eea?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-hl-categories',
        type: 'CategoryGrid',
        title: 'Holi Party Stations',
        subtitle: 'Everything for your colorful backyard & terrace party',
        categoryIds: ['cat-sweets', 'cat-beverages', 'cat-snacks', 'cat-pooja', 'cat-dairy', 'cat-dryfruits'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-hl-gujiya',
        type: 'ProductCarousel',
        title: 'Hot Mawa Gujiya & Sweets',
        subtitle: 'Crispy outer crust filled with rich khoya and dry fruits',
        badge: 'FESTIVE SPECIAL',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-hl-thandai',
        type: 'ProductCarousel',
        title: 'Thandai, Syrups & Cold Beverages',
        subtitle: 'Badam Thandai syrup, Soda, Juices & Ice Cubes for non-stop celebrations',
        badge: 'COOL & CRISP',
        categoryId: 'cat-beverages',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-hl-offer',
        type: 'OfferBanner',
        title: 'HOLI PARTY PACK: BUY 2 GET 1 FREE',
        subtitle: 'On all snacks, chips, cold drinks & disposable cups',
        badge: 'PARTY SAVER',
        tag: 'B2G1 FREE',
        ctaText: 'SHOP PARTY PACKS',
        ctaLink: '/category/snacks-beverages',
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 05: DUSSEHRA ──
  {
    id: 'tpl-dussehra-victory-fest',
    name: 'Dussehra Vijayadashami Special',
    description: 'Auspicious sunlit golden and deep royal indigo theme celebrating victory of good over evil with sweets and family feasts.',
    festivalKey: 'dussehra',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1574786198875-49f5d09fe2d5?auto=format&fit=crop&w=600&q=80',
    tags: ['Dussehra', 'Vijayadashami', 'Jalebi', 'Fafda', 'Sweets'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#CA8A04', // Rich Imperial Gold
      secondaryColor: '#1E3A8A', // Royal Navy
      accentColor: '#FEF08A',
      bgColor: '#FEFCE8',
      bgGradient: 'linear-gradient(135deg, #FEFCE8 0%, #FEF08A 50%, #FDE047 100%)',
      cardBg: '#FFFFFF',
      textColor: '#713F12',
      accentTextColor: '#A16207',
      badgeBg: '#EAB308',
      badgeTextColor: '#422006',
      mood: 'traditional_indian',
      fontStyle: 'festive_serif',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-ds-hero',
        type: 'Hero',
        title: 'Happy Dussehra & Vijayadashami 🏹',
        subtitle: 'Celebrate new beginnings with crunchy hot Jalebi-Fafda, Shrikhand, Puja Samagri & Family Feasts.',
        badge: 'AUSPICIOUS CELEBRATIONS',
        ctaText: 'ORDER DUSSEHRA SPECIALS',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1574786198875-49f5d09fe2d5?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1574786198875-49f5d09fe2d5?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-ds-categories',
        type: 'CategoryGrid',
        title: 'Dussehra Feast Essentials',
        subtitle: 'Everything for your festive rituals and celebratory brunch',
        categoryIds: ['cat-sweets', 'cat-snacks', 'cat-pooja', 'cat-oil', 'cat-dairy', 'cat-staples'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-ds-jalebi',
        type: 'ProductCarousel',
        title: 'Jalebi, Fafda & Sweet Treats',
        subtitle: 'Fresh hot morning deliveries for Vijayadashami breakfast',
        badge: 'MORNING SPECIAL',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-ds-feasts',
        type: 'Collection',
        title: 'Pantry Cooking & Feast Staples',
        subtitle: 'Basmati Rice, Pure Ghee, Atta, Besan & Cooking Oils',
        badge: 'FEAST PREP',
        categoryId: 'cat-staples',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 06: EID ──
  {
    id: 'tpl-eid-mubarak-royal',
    name: 'Eid Mubarak Royal Feast',
    description: 'Emerald green, shimmering gold and velvet aesthetic for Sheer Khurma, Biryani spices, Dates & Hosting essentials.',
    festivalKey: 'eid',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=600&q=80',
    tags: ['Eid', 'Dates', 'Seviyan', 'Biryani', 'Green', 'Gold'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#059669', // Royal Emerald Green
      secondaryColor: '#064E3B',
      accentColor: '#FDE047', // Shimmering Gold
      bgColor: '#ECFDF5',
      bgGradient: 'linear-gradient(135deg, #064E3B 0%, #065F46 50%, #047857 100%)',
      cardBg: '#FFFFFF',
      textColor: '#064E3B',
      accentTextColor: '#059669',
      badgeBg: '#10B981',
      badgeTextColor: '#FFFFFF',
      mood: 'premium_festive',
      fontStyle: 'festive_serif',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-eid-hero',
        type: 'Hero',
        title: 'Eid Mubarak! 🌙✨',
        subtitle: 'Premium Medjool Dates, Roasted Seviyan, Biryani Basmati & Gourmet Dry Fruits for your grand feast.',
        badge: 'FESTIVAL OF JOY',
        ctaText: 'SHOP EID SPECIALS',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-eid-categories',
        type: 'CategoryGrid',
        title: 'Eid Feast Stations',
        subtitle: 'Authentic ingredients for Sheer Khurma and Dawat preparation',
        categoryIds: ['cat-dryfruits', 'cat-dairy', 'cat-staples', 'cat-sweets', 'cat-beverages', 'cat-oil'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-eid-dates',
        type: 'ProductCarousel',
        title: 'Imported Dates & Dry Fruits',
        subtitle: 'Ajwa, Medjool, Kimia Dates, Almonds & Pistachios',
        badge: 'ROYAL SELECTION',
        categoryId: 'cat-dryfruits',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-eid-biryani',
        type: 'Collection',
        title: 'Grand Biryani & Dawat Staples',
        subtitle: 'Daawat Basmati, Whole Spices, Shahi Masala & Pure Ghee',
        badge: 'DAWAT READY',
        categoryId: 'cat-staples',
        active: true,
      },
      {
        id: 'sec-eid-offer',
        type: 'OfferBanner',
        title: 'FLAT ₹150 OFF ON EID GROCERY BASKET',
        subtitle: 'Use code EIDFEAST on orders above ₹799',
        badge: 'FESTIVE CODE',
        tag: 'SPECIAL SAVINGS',
        ctaText: 'REDEEM NOW',
        ctaLink: '/category/staples',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 07: CHRISTMAS ──
  {
    id: 'tpl-christmas-winter-wonder',
    name: 'Christmas Baking & Cheer',
    description: 'Festive winter pine green and velvet red theme packed with baking supplies, chocolates, plum cakes & party hampers.',
    festivalKey: 'christmas',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=600&q=80',
    tags: ['Christmas', 'Cakes', 'Chocolates', 'Baking', 'Winter', 'Party'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#DC2626', // Velvet Christmas Red
      secondaryColor: '#15803D', // Pine Forest Green
      accentColor: '#FEF08A',
      bgColor: '#FEF2F2',
      bgGradient: 'linear-gradient(135deg, #14532D 0%, #166534 50%, #991B1B 100%)',
      cardBg: '#FFFFFF',
      textColor: '#7F1D1D',
      accentTextColor: '#DC2626',
      badgeBg: '#16A34A',
      badgeTextColor: '#FFFFFF',
      mood: 'premium_festive',
      fontStyle: 'clean_modern',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-xm-hero',
        type: 'Hero',
        title: 'Merry Christmas & Joy! 🎄🎁',
        subtitle: 'Authentic Rich Plum Cakes, Baking Essentials, Cocoa, Gourmet Chocolates & Holiday Hampers.',
        badge: 'HOLIDAY SEASON',
        ctaText: 'EXPLORE CHRISTMAS AISLE',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-xm-categories',
        type: 'CategoryGrid',
        title: 'Holiday Special Categories',
        subtitle: 'All your festive baking, chocolates & party drinks',
        categoryIds: ['cat-bakery', 'cat-chocolates', 'cat-beverages', 'cat-dairy', 'cat-snacks', 'cat-dryfruits'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-xm-baking',
        type: 'ProductCarousel',
        title: 'Cakes & Home Baking Studio',
        subtitle: 'Plum Cakes, Vanilla Extract, Cocoa Powder, Baking Chips & Butter',
        badge: 'BAKER’S CHOICE',
        categoryId: 'cat-bakery',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-xm-chocolates',
        type: 'ProductCarousel',
        title: 'Chocolates & Gift Boxes',
        subtitle: 'Cadbury Celebrations, Ferrero Rocher, Lindt & Hershey’s',
        badge: 'GIFT READY',
        categoryId: 'cat-chocolates',
        maxItems: 8,
        active: true,
      },
    ],
  },

  // ── TEMPLATE 08: NEW YEAR ──
  {
    id: 'tpl-new-year-party-countdown',
    name: 'New Year Midnight Party & Recovery',
    description: 'Sleek midnight blue and electric champagne gold quick commerce look for midnight party snacks, sodas & next-day breakfast.',
    festivalKey: 'new_year',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?auto=format&fit=crop&w=600&q=80',
    tags: ['New Year', 'Party', 'Drinks', 'Midnight', 'Snacks'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#6366F1', // Indigo Neon
      secondaryColor: '#0F172A', // Midnight Slate
      accentColor: '#FDE047', // Champagne Gold
      bgColor: '#0F172A',
      bgGradient: 'linear-gradient(135deg, #020617 0%, #0F172A 50%, #1E1B4B 100%)',
      cardBg: '#1E293B',
      textColor: '#F8FAFC',
      accentTextColor: '#A5B4FC',
      badgeBg: '#EAB308',
      badgeTextColor: '#0F172A',
      mood: 'modern_quick_commerce',
      fontStyle: 'bold_display',
      borderRadius: 'pill',
    },
    sections: [
      {
        id: 'sec-ny-hero',
        type: 'Hero',
        title: 'Welcome 2027 In Style! 🎆🍾',
        subtitle: 'Non-stop midnight deliveries of Chips, Dips, Ice Cubes, Sodas, Mocktails & Next-Morning Breakfast.',
        badge: 'MIDNIGHT EXPRESS',
        ctaText: 'STOCK UP FOR THE PARTY',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-ny-countdown',
        type: 'Countdown',
        title: 'Midnight Countdown & Flash Sale',
        badge: 'CLOCK TICKING',
        targetDate: '2026-12-31T23:59:59.000Z',
        active: true,
      },
      {
        id: 'sec-ny-categories',
        type: 'CategoryGrid',
        title: 'Party Supply Stations',
        subtitle: 'Instant munchies, cold beverages and morning recovery',
        categoryIds: ['cat-snacks', 'cat-beverages', 'cat-dairy', 'cat-bakery', 'cat-chocolates'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-ny-snacks',
        type: 'ProductCarousel',
        title: 'Midnight Munchies & Party Dips',
        subtitle: 'Nachos, Salsa, Makhana, Popcorn & Instant Pizzas',
        badge: 'INSTANT CRAVINGS',
        categoryId: 'cat-snacks',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-ny-drinks',
        type: 'ProductCarousel',
        title: 'Sodas, Energy Drinks & Juices',
        subtitle: 'Chilled Coke, Red Bull, Tonic Water & Fresh Fruit Juices',
        badge: 'CHILLED DELIVERY',
        categoryId: 'cat-beverages',
        maxItems: 8,
        active: true,
      },
    ],
  },

  // ── TEMPLATE 09: HARTALIKA TEEJ ──
  {
    id: 'tpl-hartalika-teej-green',
    name: 'Hartalika Teej Shringaar & Sweets',
    description: 'Fresh emerald and bridal green Indian ethnic look with Ghevar, Puja Samagri, Mehndi & seasonal fruits.',
    festivalKey: 'teej',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=600&q=80',
    tags: ['Teej', 'Ghevar', 'Puja', 'Green', 'Fasting'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#15803D', // Emerald Green
      secondaryColor: '#14532D',
      accentColor: '#FDE047', // Zari Gold
      bgColor: '#F0FDF4',
      bgGradient: 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 50%, #BBF7D0 100%)',
      cardBg: '#FFFFFF',
      textColor: '#14532D',
      accentTextColor: '#16A34A',
      badgeBg: '#22C55E',
      badgeTextColor: '#FFFFFF',
      mood: 'traditional_indian',
      fontStyle: 'festive_serif',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-tj-hero',
        type: 'Hero',
        title: 'Happy Hartalika Teej! 🌿🦚',
        subtitle: 'Authentic Malai Ghevar, Pure Puja Samagri, Shringaar items & Fresh Orchard Fruits delivered fast.',
        badge: 'SACRED CELEBRATION',
        ctaText: 'SHOP TEEJ SAMAGRI',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-tj-ghevar',
        type: 'ProductCarousel',
        title: 'Special Malai & Kesar Ghevar',
        subtitle: 'Handcrafted honeycomb delicacy soaked in saffron syrup',
        badge: 'SEASONAL FAVORITE',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-tj-puja',
        type: 'Collection',
        title: 'Teej Vrat & Puja Samagri Kit',
        subtitle: 'Shiv-Parvati puja essentials, Gangajal, Supari & Agarbatti',
        badge: 'COMPLETE SAMAGRI',
        categoryId: 'cat-pooja',
        active: true,
      },
    ],
  },

  // ── TEMPLATE 10: CUSTOM UNIVERSAL FESTIVAL ──
  {
    id: 'tpl-custom-universal-festival',
    name: 'Universal Indian Festival Base',
    description: 'Fully customizable, adaptable layout for regional festivals (Makar Sankranti, Gudi Padwa, Baisakhi, Rakhi, Onam, Pongal, etc.) with dynamic modular components.',
    festivalKey: 'custom',
    category: 'SYSTEM',
    version: 1,
    schemaVersion: '1.0',
    minimumAppVersion: '1.0.0',
    previewThumbnail: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=600&q=80',
    tags: ['Custom', 'Universal', 'Multi-purpose', 'Modular'],
    createdBy: 'Pocket Kirana Design System',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
    theme: {
      primaryColor: '#059669', // Emerald
      secondaryColor: '#064E3B',
      accentColor: '#FEF08A',
      bgColor: '#F0FDF4',
      bgGradient: 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 50%, #FEF3C7 100%)',
      cardBg: '#FFFFFF',
      textColor: '#064E3B',
      accentTextColor: '#059669',
      badgeBg: '#10B981',
      badgeTextColor: '#FFFFFF',
      mood: 'premium_festive',
      fontStyle: 'clean_modern',
      borderRadius: 'curved',
    },
    sections: [
      {
        id: 'sec-cu-hero',
        type: 'Hero',
        title: 'Festival Greetings from Pocket Kirana!',
        subtitle: 'Shop the freshest grocery, authentic sweets, puja essentials & home delicacies with 10-minute delivery.',
        badge: 'FESTIVE CELEBRATION',
        ctaText: 'EXPLORE SPECIALS',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1200&q=80',
        mobileImage: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=600&q=80',
        active: true,
      },
      {
        id: 'sec-cu-categories',
        type: 'CategoryGrid',
        title: 'Festival Shopping Aisles',
        subtitle: 'Curated grocery categories for celebration and feasting',
        categoryIds: ['cat-sweets', 'cat-pooja', 'cat-fruits', 'cat-dryfruits', 'cat-snacks'],
        layoutStyle: 'grid',
        active: true,
      },
      {
        id: 'sec-cu-products',
        type: 'ProductCarousel',
        title: 'Festival Bestsellers',
        subtitle: 'Most ordered items for today’s celebration',
        badge: 'TOP PICKS',
        categoryId: 'cat-sweets',
        maxItems: 8,
        active: true,
      },
      {
        id: 'sec-cu-offer',
        type: 'OfferBanner',
        title: 'FESTIVE SAVINGS: FLAT ₹75 OFF',
        subtitle: 'On your first 3 festival orders with code FESTIVE75',
        badge: 'SPECIAL DISCOUNT',
        tag: 'LIMITED OFFER',
        ctaText: 'START SAVING',
        ctaLink: '/categories',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
        active: true,
      },
    ],
  },
];
