import {
  Category,
  Brand,
  Product,
  Store,
  Banner,
  Coupon,
  DeliveryPartner,
  PartnerPricingRules,
  StorageLocation,
  InventoryMovement,
  PickingTask,
  Picker,
  StockAdjustmentRequest,
  NewProductRequest,
  Address,
  Order,
  Review,
  Notification,
  AuditLog,
  SupportTicket
} from '@/types';

export const INITIAL_STORAGE_LOCATIONS: StorageLocation[] = [
  {
    id: 'loc-a01-a01',
    storeId: 'store-1',
    aisle: 'Aisle A (Staples & Grains)',
    rack: '01',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-A01A01',
    displayCode: 'A-01-A-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-a01-a02',
    storeId: 'store-1',
    aisle: 'Aisle A (Staples & Grains)',
    rack: '01',
    shelf: 'A',
    bin: '02',
    barcode: 'LOC-A01A02',
    displayCode: 'A-01-A-02',
    zone: 'Ambient',
  },
  {
    id: 'loc-a02-b01',
    storeId: 'store-1',
    aisle: 'Aisle A (Staples & Grains)',
    rack: '02',
    shelf: 'B',
    bin: '01',
    barcode: 'LOC-A02B01',
    displayCode: 'A-02-B-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-a02-b04',
    storeId: 'store-1',
    aisle: 'Aisle A (Staples & Grains)',
    rack: '02',
    shelf: 'B',
    bin: '04',
    barcode: 'LOC-A02B04',
    displayCode: 'A-02-B-04',
    zone: 'Ambient',
  },
  {
    id: 'loc-b01-a01',
    storeId: 'store-1',
    aisle: 'Aisle B (Snacks & Quick Bites)',
    rack: '01',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-B01A01',
    displayCode: 'B-01-A-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-b01-b02',
    storeId: 'store-1',
    aisle: 'Aisle B (Snacks & Quick Bites)',
    rack: '01',
    shelf: 'B',
    bin: '02',
    barcode: 'LOC-B01B02',
    displayCode: 'B-01-B-02',
    zone: 'Ambient',
  },
  {
    id: 'loc-b02-a01',
    storeId: 'store-1',
    aisle: 'Aisle B (Snacks & Quick Bites)',
    rack: '02',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-B02A01',
    displayCode: 'B-02-A-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-b03-c01',
    storeId: 'store-1',
    aisle: 'Aisle B (Cleaning & Household)',
    rack: '03',
    shelf: 'C',
    bin: '01',
    barcode: 'LOC-B03C01',
    displayCode: 'B-03-C-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-b03-c02',
    storeId: 'store-1',
    aisle: 'Aisle B (Personal Care)',
    rack: '03',
    shelf: 'C',
    bin: '02',
    barcode: 'LOC-B03C02',
    displayCode: 'B-03-C-02',
    zone: 'Ambient',
  },
  {
    id: 'loc-c01-a01',
    storeId: 'store-1',
    aisle: 'Aisle C (Dairy Chiller)',
    rack: '01',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-C01A01',
    displayCode: 'C-01-A-01',
    zone: 'Chilled',
  },
  {
    id: 'loc-c01-a02',
    storeId: 'store-1',
    aisle: 'Aisle C (Dairy Chiller)',
    rack: '01',
    shelf: 'A',
    bin: '02',
    barcode: 'LOC-C01A02',
    displayCode: 'C-01-A-02',
    zone: 'Chilled',
  },
  {
    id: 'loc-d01-a01',
    storeId: 'store-1',
    aisle: 'Aisle D (Fresh Fruits)',
    rack: '01',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-D01A01',
    displayCode: 'D-01-A-01',
    zone: 'Ambient',
  },
  {
    id: 'loc-d02-a01',
    storeId: 'store-1',
    aisle: 'Aisle D (Fresh Veggies)',
    rack: '02',
    shelf: 'A',
    bin: '01',
    barcode: 'LOC-D02A01',
    displayCode: 'D-02-A-01',
    zone: 'Ambient',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // 1. Fruits & Vegetables
  {
    id: 'cat-veg',
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=200&q=80',
    description: 'Farm-fresh daily vegetables, organic produce and seasonal fruits',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-fresh-veg',
    parentId: 'cat-veg',
    name: 'Fresh Vegetables',
    slug: 'fresh-vegetables',
    image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=200&q=80',
    description: 'Potatoes, tomatoes, onions, leafy greens & daily kitchen staples',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-fresh-fruits',
    parentId: 'cat-veg',
    name: 'Fresh Fruits',
    slug: 'fresh-fruits',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=200&q=80',
    description: 'Fresh apples, bananas, citrus, papayas and seasonal fruits',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-exotic-fruits',
    parentId: 'cat-veg',
    name: 'Exotic Fruits',
    slug: 'exotic-fruits',
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=200&q=80',
    description: 'Kiwi, avocado, dragon fruit, blueberries and imported fresh fruits',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-exotic-veg',
    parentId: 'cat-veg',
    name: 'Exotic Vegetables',
    slug: 'exotic-vegetables',
    image: 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&w=200&q=80',
    description: 'Broccoli, lettuce, colored capsicum, zucchini and mushrooms',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'sub-organic',
    parentId: 'cat-veg',
    name: 'Organic Produce',
    slug: 'organic-produce',
    image: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=200&q=80',
    description: 'Certified pesticide-free organic fresh vegetables & fruits',
    sortOrder: 5,
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'sub-seasons-best',
    parentId: 'cat-veg',
    name: "Season's Best",
    slug: 'seasons-best',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=200&q=80',
    description: 'Peak season fresh arrivals handpicked for best sweetness & flavor',
    sortOrder: 6,
    displayOrder: 6,
    isActive: true,
  },

  // 2. Oil & Ghee
  {
    id: 'cat-oil-ghee',
    name: 'Oil & Ghee',
    slug: 'oil-ghee',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    description: 'Pure desi ghee, mustard oil, refined cooking oils & cold pressed oils',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-cooking-oil',
    parentId: 'cat-oil-ghee',
    name: 'Cooking Oil',
    slug: 'cooking-oil',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    description: 'Refined sunflower, soybean, rice bran and blended cooking oils',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-ghee',
    parentId: 'cat-oil-ghee',
    name: 'Desi Ghee',
    slug: 'desi-ghee',
    image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=200&q=80',
    description: 'Pure cow ghee, buffalo ghee and A2 bilona desi ghee',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-mustard-oil',
    parentId: 'cat-oil-ghee',
    name: 'Mustard Oil',
    slug: 'mustard-oil',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    description: 'Kachi ghani cold pressed pure mustard oil',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-sunflower-oil',
    parentId: 'cat-oil-ghee',
    name: 'Sunflower Oil',
    slug: 'sunflower-oil',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    description: 'Light and healthy refined sunflower cooking oil',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'sub-groundnut-oil',
    parentId: 'cat-oil-ghee',
    name: 'Groundnut Oil',
    slug: 'groundnut-oil',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    description: 'Cold pressed & filtered pure groundnut peanut cooking oil',
    sortOrder: 5,
    displayOrder: 5,
    isActive: true,
  },

  // 3. Dairy & Breakfast
  {
    id: 'cat-dairy',
    name: 'Dairy & Breakfast',
    slug: 'dairy-breakfast',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=200&q=80',
    description: 'Fresh milk, butter, paneer, curd, cheese, bread and eggs',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-milk-cream',
    parentId: 'cat-dairy',
    name: 'Milk & Cream',
    slug: 'milk-cream',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=200&q=80',
    description: 'Cow milk, toned milk, full cream pouch milk & fresh dairy cream',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-butter-spreads',
    parentId: 'cat-dairy',
    name: 'Butter & Spreads',
    slug: 'butter-spreads',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=200&q=80',
    description: 'Salted butter, unsalted white butter, peanut butter and cheese spreads',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-paneer-curd',
    parentId: 'cat-dairy',
    name: 'Paneer & Curd',
    slug: 'paneer-curd',
    image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=200&q=80',
    description: 'Fresh malai paneer, thick dahi curd, lassi and Greek yogurt',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-bread-eggs',
    parentId: 'cat-dairy',
    name: 'Bread & Eggs',
    slug: 'bread-eggs',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    description: 'Brown bread, white sandwich bread, pav, fresh farm eggs and brown eggs',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'sub-cereal-oats',
    parentId: 'cat-dairy',
    name: 'Cereal & Oats',
    slug: 'cereal-oats',
    image: 'https://images.unsplash.com/photo-1521483451569-e33803c0330c?auto=format&fit=crop&w=200&q=80',
    description: 'Rolled oats, muesli, cornflakes and crunchy granola',
    sortOrder: 5,
    displayOrder: 5,
    isActive: true,
  },

  // 4. Staples & Grains
  {
    id: 'cat-staples',
    name: 'Staples & Grains',
    slug: 'staples',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=200&q=80',
    description: 'Atta, flours, rice, dals, pulses, spices and cooking essentials',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'sub-atta-flours',
    parentId: 'cat-staples',
    name: 'Atta & Flours',
    slug: 'atta-flours',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    description: 'Chakki fresh whole wheat atta, maida, besan, sooji and multigrain flours',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-rice-poha',
    parentId: 'cat-staples',
    name: 'Rice & Poha',
    slug: 'rice-poha',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=200&q=80',
    description: 'Basmati rice, kolam rice, sona masoori, thick poha and murmura',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-dals-pulses',
    parentId: 'cat-staples',
    name: 'Dals & Pulses',
    slug: 'dals-pulses',
    image: 'https://images.unsplash.com/photo-1515942400420-2b98fed1f515?auto=format&fit=crop&w=200&q=80',
    description: 'Toor dal, moong dal, chana dal, urad dal, rajma and kabuli chana',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-spices-salt',
    parentId: 'cat-staples',
    name: 'Spices, Salt & Sugar',
    slug: 'spices-salt-sugar',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=200&q=80',
    description: 'Turmeric, red chilli powder, coriander powder, whole garam masala, salt & sugar',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },

  // 5. Snacks & Munchies
  {
    id: 'cat-snacks',
    name: 'Snacks & Munchies',
    slug: 'snacks-munchies',
    image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=200&q=80',
    description: 'Chips, namkeen, instant noodles, chocolates, sweets and cookies',
    sortOrder: 5,
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'sub-chips-namkeen',
    parentId: 'cat-snacks',
    name: 'Chips & Namkeen',
    slug: 'chips-namkeen',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=200&q=80',
    description: 'Potato chips, bhujia, sev, mixture, roasted peanuts and kurkure',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-noodles-pasta',
    parentId: 'cat-snacks',
    name: 'Instant Noodles & Pasta',
    slug: 'instant-noodles-pasta',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=200&q=80',
    description: 'Maggi, ramen noodles, macaroni, penne pasta and pasta sauces',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-biscuits-cookies',
    parentId: 'cat-snacks',
    name: 'Biscuits & Cookies',
    slug: 'biscuits-cookies',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=200&q=80',
    description: 'Glucose biscuits, cream cookies, digestive crackers and cookies',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-chocolates-sweets',
    parentId: 'cat-snacks',
    name: 'Chocolates & Sweets',
    slug: 'chocolates-sweets',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=200&q=80',
    description: 'Dairy Milk, KitKat, 5Star, gulab jamun, rasgulla and traditional Indian sweets',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },

  // 6. Beverages
  {
    id: 'cat-drinks',
    name: 'Beverages',
    slug: 'beverages',
    image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?auto=format&fit=crop&w=200&q=80',
    description: 'Tea, coffee, soft drinks, juices, energy drinks and water',
    sortOrder: 6,
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'sub-tea-coffee',
    parentId: 'cat-drinks',
    name: 'Tea & Coffee',
    slug: 'tea-coffee',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=200&q=80',
    description: 'Chai patti, green tea, instant coffee powder and filter coffee',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-soft-drinks',
    parentId: 'cat-drinks',
    name: 'Soft Drinks & Juices',
    slug: 'soft-drinks-juices',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=200&q=80',
    description: 'Cola, lemon soda, mango juice, real fruit juices and coconut water',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-health-drinks',
    parentId: 'cat-drinks',
    name: 'Health & Energy Drinks',
    slug: 'health-energy-drinks',
    image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?auto=format&fit=crop&w=200&q=80',
    description: 'Horlicks, Bournvita, Red Bull and protein health supplements',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },

  // 7. Personal Care
  {
    id: 'cat-personal',
    name: 'Personal Care',
    slug: 'personal-care',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=80',
    description: 'Soaps, shampoos, hair oils, toothpastes, skincare and grooming',
    sortOrder: 7,
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'sub-bath-soaps',
    parentId: 'cat-personal',
    name: 'Bath & Soaps',
    slug: 'bath-soaps',
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=200&q=80',
    description: 'Bathing soaps, body wash, shower gels and hand washes',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-hair-care',
    parentId: 'cat-personal',
    name: 'Hair Care',
    slug: 'hair-care',
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=200&q=80',
    description: 'Shampoos, conditioners, hair oils and styling gels',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-oral-care',
    parentId: 'cat-personal',
    name: 'Oral Care',
    slug: 'oral-care',
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=200&q=80',
    description: 'Toothpaste, toothbrushes, tongue cleaners and mouthwashes',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sub-skincare',
    parentId: 'cat-personal',
    name: 'Skincare & Creams',
    slug: 'skincare-creams',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=80',
    description: 'Face wash, body lotions, moisturizers, cold creams and sunscreens',
    sortOrder: 4,
    displayOrder: 4,
    isActive: true,
  },

  // 8. Household
  {
    id: 'cat-household',
    name: 'Household Care',
    slug: 'household',
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=200&q=80',
    description: 'Detergents, floor cleaners, dishwashing bars, insect repellents and pooja essentials',
    sortOrder: 8,
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'sub-detergents',
    parentId: 'cat-household',
    name: 'Detergents & Fabric Care',
    slug: 'detergents-fabric-care',
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=200&q=80',
    description: 'Washing powder, liquid detergents, fabric conditioners and bar soaps',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-cleaners',
    parentId: 'cat-household',
    name: 'Cleaners & Disinfectants',
    slug: 'cleaners-disinfectants',
    image: 'https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=200&q=80',
    description: 'Floor cleaners, toilet cleaners, glass cleaners and surface sprays',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-dishwash',
    parentId: 'cat-household',
    name: 'Dishwash & Tools',
    slug: 'dishwash-tools',
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=200&q=80',
    description: 'Dishwash bars, gels, scrubs, sponges and steel wool',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },

  // 9. Baby Care
  {
    id: 'cat-baby',
    name: 'Baby Care',
    slug: 'baby-care',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=200&q=80',
    description: 'Baby diapers, wipes, baby food, cereals, baby soaps and lotions',
    sortOrder: 9,
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'sub-diapers-wipes',
    parentId: 'cat-baby',
    name: 'Diapers & Wipes',
    slug: 'diapers-wipes',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=200&q=80',
    description: 'Baby pant diapers, taped diapers, wet wipes and diaper rash cream',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-baby-food',
    parentId: 'cat-baby',
    name: 'Baby Food & Formula',
    slug: 'baby-food-formula',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=200&q=80',
    description: 'Cerelac, infant milk formula, purees and organic baby cereal',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-baby-bath',
    parentId: 'cat-baby',
    name: 'Baby Bath & Skincare',
    slug: 'baby-bath-skincare',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=200&q=80',
    description: 'Baby shampoo, body wash, massage oil and gentle baby powder',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },

  // 10. Bakery & Biscuits
  {
    id: 'cat-bakery',
    name: 'Bakery & Biscuits',
    slug: 'bakery-biscuits',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=200&q=80',
    description: 'Artisan breads, pav, cakes, muffins, rusk and gourmet cookies',
    sortOrder: 10,
    displayOrder: 10,
    isActive: true,
  },
  {
    id: 'sub-breads-pav',
    parentId: 'cat-bakery',
    name: 'Breads & Pav',
    slug: 'breads-pav',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    description: 'Sandwich white bread, brown bread, pav, burger buns and garlic bread',
    sortOrder: 1,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sub-cakes-muffins',
    parentId: 'cat-bakery',
    name: 'Cakes & Muffins',
    slug: 'cakes-muffins',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=200&q=80',
    description: 'Tea cakes, chocolate muffins, brownies, swiss rolls and celebration cakes',
    sortOrder: 2,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sub-rusk-toast',
    parentId: 'cat-bakery',
    name: 'Rusk, Khari & Toast',
    slug: 'rusk-khari-toast',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=200&q=80',
    description: 'Crispy suji rusk, butter khari, jeera toast and tea snacks',
    sortOrder: 3,
    displayOrder: 3,
    isActive: true,
  },
];

export const INITIAL_BRANDS: Brand[] = [
  {
    id: 'brand-fortune',
    name: 'Fortune',
    slug: 'fortune',
    logo: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    description: 'Fortune cooking oils, basmati rice, chakki fresh atta, and kitchen essentials for healthy homes.',
    isActive: true,
    status: 'active',
    displayOrder: 1,
    categoryIds: ['cat-oil-ghee', 'cat-staples'],
    productCount: 2,
  },
  {
    id: 'brand-amul',
    name: 'Amul',
    slug: 'amul',
    logo: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=1200&q=80',
    description: 'Amul - The Taste of India. Pure pasteurized milk, golden butter, paneer and dairy delicacies.',
    isActive: true,
    status: 'active',
    displayOrder: 2,
    categoryIds: ['cat-dairy', 'cat-bakery', 'cat-oil-ghee'],
    productCount: 4,
  },
  {
    id: 'brand-aashirvaad',
    name: 'Aashirvaad',
    slug: 'aashirvaad',
    logo: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
    description: 'Aashirvaad whole wheat chakki atta, unpolished pulses and authentic Indian spices.',
    isActive: true,
    status: 'active',
    displayOrder: 3,
    categoryIds: ['cat-staples'],
    productCount: 2,
  },
  {
    id: 'brand-lays',
    name: "Lay's",
    slug: 'lays',
    logo: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80',
    description: "Crispy, flavorful, farm-grown potato chips made with authentic spices.",
    isActive: true,
    status: 'active',
    displayOrder: 4,
    categoryIds: ['cat-snacks'],
    productCount: 2,
  },
  {
    id: 'brand-britannia',
    name: 'Britannia',
    slug: 'britannia',
    logo: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
    description: 'Britannia biscuits, fresh breads, butter cookies, rusk and teatime treats.',
    isActive: true,
    status: 'active',
    displayOrder: 5,
    categoryIds: ['cat-bakery', 'cat-dairy', 'cat-snacks'],
    productCount: 2,
  },
  {
    id: 'brand-mother-dairy',
    name: 'Mother Dairy',
    slug: 'mother-dairy',
    logo: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=1200&q=80',
    description: 'Pure, fresh cow & toned milk, curd, fruit drinks, and ice creams.',
    isActive: true,
    status: 'active',
    displayOrder: 6,
    categoryIds: ['cat-dairy', 'cat-drinks'],
    productCount: 1,
  },
  {
    id: 'brand-tata',
    name: 'Tata',
    slug: 'tata',
    logo: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80',
    description: 'Tata Sampann & Tata Salt - unpolished pulses, iodized salt, premium tea and spices.',
    isActive: true,
    status: 'active',
    displayOrder: 7,
    categoryIds: ['cat-staples', 'cat-drinks'],
    productCount: 1,
  },
  {
    id: 'brand-saffola',
    name: 'Saffola',
    slug: 'saffola',
    logo: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=1200&q=80',
    description: 'Saffola Gold blended edible oils and 100% natural rolled oats.',
    isActive: true,
    status: 'active',
    displayOrder: 8,
    categoryIds: ['cat-oil-ghee', 'cat-staples'],
    productCount: 1,
  },
  {
    id: 'brand-dettol',
    name: 'Dettol',
    slug: 'dettol',
    logo: 'https://images.unsplash.com/photo-1608248597359-593b4a2c534c?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1608248597359-593b4a2c534c?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80',
    description: 'Dettol antiseptic liquid, germ protection bathing soaps and hygiene essentials.',
    isActive: true,
    status: 'active',
    displayOrder: 9,
    categoryIds: ['cat-personal', 'cat-household'],
    productCount: 1,
  },
  {
    id: 'brand-surf-excel',
    name: 'Surf Excel',
    slug: 'surf-excel',
    logo: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=1200&q=80',
    description: 'Surf Excel Matic liquids and detergent powders for tough stain removal.',
    isActive: true,
    status: 'active',
    displayOrder: 10,
    categoryIds: ['cat-household'],
    productCount: 1,
  },
  {
    id: 'brand-patanjali',
    name: 'Patanjali',
    slug: 'patanjali',
    logo: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    description: 'Patanjali pure cow ghee, organic honey, herbal dental care, and wellness.',
    isActive: true,
    status: 'active',
    displayOrder: 11,
    categoryIds: ['cat-oil-ghee', 'cat-staples', 'cat-personal'],
    productCount: 1,
  },
  {
    id: 'brand-real',
    name: 'Real',
    slug: 'real',
    logo: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=1200&q=80',
    description: 'Real Fruit Power 100% pure juices and refreshing fruit beverages.',
    isActive: true,
    status: 'active',
    displayOrder: 12,
    categoryIds: ['cat-drinks'],
    productCount: 1,
  },
  {
    id: 'brand-farm-fresh',
    name: 'Farm Fresh Organic',
    slug: 'farm-fresh-organic',
    logo: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',
    description: 'Directly sourced organic fresh fruits, leafy vegetables and handpicked farm produce.',
    isActive: true,
    status: 'active',
    displayOrder: 13,
    categoryIds: ['cat-veg'],
    productCount: 15,
  },
  {
    id: 'brand-nandini',
    name: 'Nandini',
    slug: 'nandini',
    logo: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=200&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=1200&q=80',
    description: 'Nandini pure fresh milk, curd, butter and dairy products by KMF.',
    isActive: true,
    status: 'active',
    displayOrder: 14,
    categoryIds: ['cat-dairy'],
    productCount: 1,
  },
];

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-1',
    storeCode: 'STORE001',
    ownerId: 'usr-admin-1',
    name: 'PocketKirana Store - Neral Hub',
    phone: '+91 98201 23456',
    email: 'neral.hub@pocketkirana.com',
    gstNumber: '27AAAAA0000A1Z5',
    address: 'Matoshree Nagar, Neral, Karjat, Maharashtra',
    city: 'Neral',
    state: 'Maharashtra',
    pincode: '410101',
    latitude: 18.9876,
    longitude: 73.321,
    openingTime: '06:00',
    closingTime: '23:00',
    deliveryRadiusKm: 3.0,
    maxRoadDistanceKm: 4.5,
    roadDistanceMultiplier: 1.35,
    minimumOrderValue: 199,
    deliveryFee: 15,
    expressDeliveryEnabled: true,
    status: 'active',
    deliveryStatus: 'ACTIVE',
  },
  {
    id: 'store-2',
    storeCode: 'STORE002',
    ownerId: 'usr-admin-1',
    name: 'PocketKirana Store - Karjat Central',
    phone: '+91 98201 23457',
    email: 'karjat.hub@pocketkirana.com',
    gstNumber: '27AAAAA0000A1Z6',
    address: 'Station Road, Karjat, Maharashtra',
    city: 'Karjat',
    state: 'Maharashtra',
    pincode: '410201',
    latitude: 18.9102,
    longitude: 73.3284,
    openingTime: '06:00',
    closingTime: '23:00',
    deliveryRadiusKm: 5.0,
    maxRoadDistanceKm: 7.0,
    roadDistanceMultiplier: 1.35,
    minimumOrderValue: 249,
    deliveryFee: 20,
    expressDeliveryEnabled: true,
    status: 'active',
    deliveryStatus: 'ACTIVE',
  },
  {
    id: 'store-3',
    storeCode: 'STORE003',
    ownerId: 'usr-admin-1',
    name: 'PocketKirana Store - Badlapur East',
    phone: '+91 98201 77889',
    email: 'badlapur.hub@pocketkirana.com',
    gstNumber: '27CCCCC0000C1Z7',
    address: 'Katrap Road, Badlapur East, Maharashtra',
    city: 'Badlapur',
    state: 'Maharashtra',
    pincode: '421503',
    latitude: 19.1664,
    longitude: 73.2368,
    openingTime: '06:00',
    closingTime: '23:00',
    deliveryRadiusKm: 4.0,
    maxRoadDistanceKm: 5.5,
    roadDistanceMultiplier: 1.35,
    minimumOrderValue: 199,
    deliveryFee: 15,
    expressDeliveryEnabled: true,
    status: 'active',
    deliveryStatus: 'ACTIVE',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Milk & Dairy (Screen 4 & Screen 5)
  {
    id: 'p-milk-fresh-1l',
    categoryId: 'cat-dairy',
    brandId: 'brand-amul',
    storeId: 'store-1',
    sku: 'AML-FRSH-1L',
    barcode: '8901262010015',
    name: 'Amul Fresh Milk 1L',
    slug: 'amul-fresh-milk-1l',
    description: 'Amul Fresh Milk is a rich source of proteins and calcium. Fresh pasteurized tawa milk for everyday consumption.',
    unit: '1 L',
    weight: 1.0,
    mrp: 70,
    sellingPrice: 62,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 128,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'p-milk-gold-1l',
    categoryId: 'cat-dairy',
    brandId: 'brand-amul',
    storeId: 'store-1',
    sku: 'AML-GOLD-1L',
    barcode: '8901262010016',
    name: 'Amul Gold Milk 1L',
    slug: 'amul-gold-milk-1l',
    description: 'High fat pasteurised full cream milk ideal for thick curd and delicious tea.',
    unit: '1 L',
    weight: 1.0,
    mrp: 72,
    sellingPrice: 68,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 310,
    isPopular: true,
  },
  {
    id: 'p-milk-md-1l',
    categoryId: 'cat-dairy',
    brandId: 'brand-mother-dairy',
    storeId: 'store-1',
    sku: 'MD-TONED-1L',
    barcode: '8901262010017',
    name: 'Mother Dairy Toned Milk 1L',
    slug: 'mother-dairy-toned-milk-1l',
    description: 'Fresh toned milk fortified with Vitamin A and Vitamin D.',
    unit: '1 L',
    weight: 1.0,
    mrp: 62,
    sellingPrice: 58,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1571217865189-d99bc2d7a02e?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 95,
    isPopular: true,
  },
  {
    id: 'p-milk-taaza-500ml',
    categoryId: 'cat-dairy',
    brandId: 'brand-amul',
    storeId: 'store-1',
    sku: 'AML-TAAZA-500ML',
    barcode: '8901262010012',
    name: 'Amul Taaza Milk 500ml',
    slug: 'amul-taaza-milk-500ml',
    description: 'Homogenised pasteurised toned milk in convenient pouch.',
    unit: '500 ml',
    weight: 0.5,
    mrp: 30,
    sellingPrice: 28,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 450,
    isPopular: true,
  },
  {
    id: 'p-milk-nandini-1l',
    categoryId: 'cat-dairy',
    brandId: 'brand-nandini',
    storeId: 'store-1',
    sku: 'NDN-FRESH-1L',
    barcode: '8901262010019',
    name: 'Nandini Fresh Milk 1L',
    slug: 'nandini-fresh-milk-1l',
    description: 'Pure and fresh pasteurised toned cow milk.',
    unit: '1 L',
    weight: 1.0,
    mrp: 65,
    sellingPrice: 60,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.6,
    reviewsCount: 88,
  },

  // Fruits & Veg (Screen 3 & Screen 1)
  {
    id: 'p-apple-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'FRU-APPLE-1KG',
    barcode: '8901111222111',
    name: 'Apple Red (1kg)',
    slug: 'apple-red-1kg',
    description: 'Fresh, crisp and sweet red apples imported daily.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 140,
    sellingPrice: 120,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 230,
    isPopular: true,
  },
  {
    id: 'p-banana-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'FRU-BANANA-1KG',
    barcode: '8901111222112',
    name: 'Banana (1kg)',
    slug: 'banana-1kg',
    description: 'Naturally ripened Robusta fresh golden bananas.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 60,
    sellingPrice: 48,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 540,
    isPopular: true,
  },
  {
    id: 'p-potato-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-POTATO-1KG',
    barcode: '8901111222113',
    name: 'Potato (1kg)',
    slug: 'potato-1kg',
    description: 'Fresh farm potatoes essential for daily Indian cooking.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 35,
    sellingPrice: 28,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.6,
    reviewsCount: 810,
    isPopular: true,
  },
  {
    id: 'p-tomato-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-TOMATO-1KG',
    barcode: '8901111222114',
    name: 'Tomato (1kg)',
    slug: 'tomato-1kg',
    description: 'Juicy red hybrid tomatoes rich in flavor and antioxidants.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 35,
    sellingPrice: 25,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 620,
    isPopular: true,
  },
  {
    id: 'p-cucumber-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-CUCUMBER-1KG',
    barcode: '8901111222115',
    name: 'Cucumber (1kg)',
    slug: 'cucumber-1kg',
    description: 'Crisp green cucumbers for salads and refreshing snacks.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 30,
    sellingPrice: 20,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.5,
    reviewsCount: 190,
  },
  {
    id: 'p-onion-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-ONION-1KG',
    barcode: '8901111222116',
    name: 'Onion (1kg)',
    slug: 'onion-1kg',
    description: 'Nashik red onions, crunchy and fragrant.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 30,
    sellingPrice: 22,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8ce?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 940,
    isPopular: true,
  },
  {
    id: 'p-carrot-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-CARROT-1KG',
    barcode: '8901111222117',
    name: 'Carrot (1kg)',
    slug: 'carrot-1kg',
    description: 'Sweet orange juicy carrots.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 40,
    sellingPrice: 30,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1598170845058-12ef4a45753b?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.6,
    reviewsCount: 310,
  },
  {
    id: 'p-capsicum-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-CAPSICUM-1KG',
    barcode: '8901111222118',
    name: 'Capsicum (1kg)',
    slug: 'capsicum-1kg',
    description: 'Fresh green bell peppers.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 50,
    sellingPrice: 40,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.6,
    reviewsCount: 220,
  },
  {
    id: 'p-beans-250g',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-BEANS-250G',
    barcode: '8901111222119',
    name: 'Beans (250g)',
    slug: 'beans-250g',
    description: 'Tender French green beans.',
    unit: '250 g',
    weight: 0.25,
    mrp: 20,
    sellingPrice: 15,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.5,
    reviewsCount: 140,
  },
  {
    id: 'p-spinach-250g',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-SPINACH-250G',
    barcode: '8901111222120',
    name: 'Spinach (250g)',
    slug: 'spinach-250g',
    description: 'Farm fresh washed green palak leaves.',
    unit: '250 g',
    weight: 0.25,
    mrp: 20,
    sellingPrice: 15,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 410,
  },
  {
    id: 'p-cauliflower-1pc',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-CAULI-1PC',
    barcode: '8901111222121',
    name: 'Cauliflower (1pc)',
    slug: 'cauliflower-1pc',
    description: 'Fresh clean white cauliflower head.',
    unit: '1 pc',
    weight: 0.8,
    mrp: 40,
    sellingPrice: 30,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 290,
  },
  {
    id: 'p-brinjal-1kg',
    categoryId: 'cat-veg',
    brandId: 'brand-farm-fresh',
    storeId: 'store-1',
    sku: 'VEG-BRINJAL-1KG',
    barcode: '8901111222122',
    name: 'Brinjal (1kg)',
    slug: 'brinjal-1kg',
    description: 'Purple glossy fresh eggplants.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 40,
    sellingPrice: 30,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.5,
    reviewsCount: 180,
  },

  // Best Sellers & Essentials (Screen 1)
  {
    id: 'p-atta-5kg',
    categoryId: 'cat-staples',
    brandId: 'brand-aashirvaad',
    storeId: 'store-1',
    sku: 'ASH-ATTA-5KG',
    barcode: '8901058001234',
    name: 'Aashirvaad Atta 5kg',
    slug: 'aashirvaad-atta-5kg',
    description: '100% pure whole wheat flour for soft rotis.',
    unit: '5 kg',
    weight: 5.0,
    mrp: 295,
    sellingPrice: 265,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 3120,
    isPopular: true,
  },
  {
    id: 'p-lays-classic-52g',
    categoryId: 'cat-snacks',
    brandId: 'brand-lays',
    storeId: 'store-1',
    sku: 'LAYS-CLASSIC-52G',
    barcode: '8901491101011',
    name: "Lay's Classic 52g",
    slug: 'lays-classic-52g',
    description: 'Crispy salted potato chips.',
    unit: '52 g',
    weight: 0.052,
    mrp: 20,
    sellingPrice: 20,
    taxPercentage: 12,
    thumbnail: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 1940,
    isPopular: true,
  },
  {
    id: 'p-fortune-oil-1l',
    categoryId: 'cat-oil',
    brandId: 'brand-fortune',
    storeId: 'store-1',
    sku: 'FRT-OIL-1L',
    barcode: '8906007280011',
    name: 'Fortune Sunflower Oil 1L',
    slug: 'fortune-sunflower-oil-1l',
    description: 'Refined sunflower oil light and healthy for everyday cooking.',
    unit: '1 L',
    weight: 1.0,
    mrp: 150,
    sellingPrice: 135,
    taxPercentage: 5,
    thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 1540,
    isPopular: true,
  },
  {
    id: 'p-tata-salt-1kg',
    categoryId: 'cat-staples',
    brandId: 'brand-tata',
    storeId: 'store-1',
    sku: 'TATA-SALT-1KG',
    barcode: '8901058002222',
    name: 'Tata Salt 1kg',
    slug: 'tata-salt-1kg',
    description: 'Vacuum evaporated iodized salt Desh Ka Namak.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 22,
    sellingPrice: 20,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 4200,
    isPopular: true,
  },
  {
    id: 'p-bread-britannia-400g',
    categoryId: 'cat-bakery',
    subcategoryId: 'sub-breads-pav',
    brandId: 'brand-britannia',
    brandName: 'Britannia',
    storeId: 'store-1',
    sku: 'BRT-BREAD-400G',
    barcode: '8901063001122',
    name: 'Britannia Whole Wheat Bread 400g',
    slug: 'britannia-whole-wheat-bread-400g',
    description: 'Soft fresh whole wheat sandwich bread made with 100% whole wheat flour.',
    unit: '400 g',
    weight: 0.4,
    mrp: 50,
    sellingPrice: 45,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 890,
  },
  {
    id: 'p-britannia-good-day-200g',
    categoryId: 'cat-bakery',
    subcategoryId: 'sub-cakes-muffins',
    brandId: 'brand-britannia',
    brandName: 'Britannia',
    storeId: 'store-1',
    sku: 'BRT-GOOD-DAY-200G',
    barcode: '8901063001123',
    name: 'Britannia Good Day Butter Cookies 200g',
    slug: 'britannia-good-day-butter-cookies-200g',
    description: 'Rich buttery crunchy cookies with a smiley face to brighten your tea time.',
    unit: '200 g',
    weight: 0.2,
    mrp: 45,
    sellingPrice: 40,
    taxPercentage: 12,
    thumbnail: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 1420,
    isPopular: true,
  },
  {
    id: 'p-britannia-rusk-200g',
    categoryId: 'cat-bakery',
    subcategoryId: 'sub-rusk-toast',
    brandId: 'brand-britannia',
    brandName: 'Britannia',
    storeId: 'store-1',
    sku: 'BRT-RUSK-200G',
    barcode: '8901063001124',
    name: 'Britannia Toastea Premium Bake Rusk 200g',
    slug: 'britannia-toastea-premium-bake-rusk-200g',
    description: 'Crispy twice-baked elaichi flavored wheat tea rusk.',
    unit: '200 g',
    weight: 0.2,
    mrp: 40,
    sellingPrice: 35,
    taxPercentage: 12,
    thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 980,
  },
  {
    id: 'p-britannia-bourbon-150g',
    categoryId: 'cat-snacks',
    subcategoryId: 'sub-biscuits',
    brandId: 'brand-britannia',
    brandName: 'Britannia',
    storeId: 'store-1',
    sku: 'BRT-BOURBON-150G',
    barcode: '8901063001125',
    name: 'Britannia Bourbon Chocolate Cream Biscuits 150g',
    slug: 'britannia-bourbon-chocolate-cream-biscuits-150g',
    description: 'Decadent chocolate sandwich biscuits with smooth rich chocolate cream and sugar sprinkles.',
    unit: '150 g',
    weight: 0.15,
    mrp: 35,
    sellingPrice: 30,
    taxPercentage: 12,
    thumbnail: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 2150,
    isPopular: true,
  },
  {
    id: 'p-britannia-cheese-slices-200g',
    categoryId: 'cat-dairy',
    subcategoryId: 'sub-paneer-curd',
    brandId: 'brand-britannia',
    brandName: 'Britannia',
    storeId: 'store-1',
    sku: 'BRT-CHEESE-200G',
    barcode: '8901063001126',
    name: 'Britannia Processed Cheese Slices 200g (10 Slices)',
    slug: 'britannia-processed-cheese-slices-200g',
    description: 'Creamy individually wrapped processed cheese slices made from pure cow milk.',
    unit: '200 g',
    weight: 0.2,
    mrp: 160,
    sellingPrice: 145,
    taxPercentage: 5,
    thumbnail: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 760,
  },
  {
    id: 'p-surf-excel-1kg',
    categoryId: 'cat-household',
    brandId: 'brand-surf-excel',
    storeId: 'store-1',
    sku: 'SRF-EXCEL-1KG',
    barcode: '8901030005511',
    name: 'Surf Excel 1kg',
    slug: 'surf-excel-1kg',
    description: 'Quick wash detergent powder for tough stain removal.',
    unit: '1 kg',
    weight: 1.0,
    mrp: 220,
    sellingPrice: 199,
    taxPercentage: 18,
    thumbnail: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 1620,
  },

  // Wishlist items (Screen 13)
  {
    id: 'p-almonds-250g',
    categoryId: 'cat-staples',
    brandId: 'brand-tata',
    storeId: 'store-1',
    sku: 'NUT-ALMOND-250G',
    barcode: '8901111999111',
    name: 'Almonds 250g',
    slug: 'almonds-250g',
    description: 'Premium California crunchy almonds.',
    unit: '250 g',
    weight: 0.25,
    mrp: 210,
    sellingPrice: 180,
    taxPercentage: 5,
    thumbnail: 'https://images.unsplash.com/photo-1508061252025-f7896f687534?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 780,
  },
  {
    id: 'p-oats-500g',
    categoryId: 'cat-dairy',
    brandId: 'brand-saffola',
    storeId: 'store-1',
    sku: 'BRK-OATS-500G',
    barcode: '8901111999112',
    name: 'Oats 500g',
    slug: 'oats-500g',
    description: '100% rolled whole grain oats for a healthy breakfast.',
    unit: '500 g',
    weight: 0.5,
    mrp: 175,
    sellingPrice: 150,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 540,
  },
  {
    id: 'p-honey-250g',
    categoryId: 'cat-staples',
    brandId: 'brand-patanjali',
    storeId: 'store-1',
    sku: 'STP-HONEY-250G',
    barcode: '8901111999113',
    name: 'Honey 250g',
    slug: 'honey-250g',
    description: '100% pure wild forest honey.',
    unit: '250 g',
    weight: 0.25,
    mrp: 165,
    sellingPrice: 140,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 910,
  },
  {
    id: 'p-greentea-100g',
    categoryId: 'cat-drinks',
    brandId: 'brand-tata',
    storeId: 'store-1',
    sku: 'DRK-GTEA-100G',
    barcode: '8901111999114',
    name: 'Green Tea 100g',
    slug: 'green-tea-100g',
    description: 'Organic antioxidant rich green tea leaves.',
    unit: '100 g',
    weight: 0.1,
    mrp: 185,
    sellingPrice: 160,
    taxPercentage: 5,
    thumbnail: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.8,
    reviewsCount: 430,
  },
  {
    id: 'p-peanutbutter-350g',
    categoryId: 'cat-dairy',
    brandId: 'brand-amul',
    storeId: 'store-1',
    sku: 'BRK-PBUTTER-350G',
    barcode: '8901111999115',
    name: 'Peanut Butter 350g',
    slug: 'peanut-butter-350g',
    description: 'High protein creamy roasted peanut spread.',
    unit: '350 g',
    weight: 0.35,
    mrp: 220,
    sellingPrice: 190,
    taxPercentage: 12,
    thumbnail: 'https://images.unsplash.com/photo-1588615419955-5228e0776cdc?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.9,
    reviewsCount: 670,
  },
  {
    id: 'p-chiaseeds-200g',
    categoryId: 'cat-staples',
    brandId: 'brand-patanjali',
    storeId: 'store-1',
    sku: 'STP-CHIA-200G',
    barcode: '8901111999116',
    name: 'Chia Seeds 200g',
    slug: 'chia-seeds-200g',
    description: 'Raw black organic superfood chia seeds.',
    unit: '200 g',
    weight: 0.2,
    mrp: 155,
    sellingPrice: 130,
    taxPercentage: 0,
    thumbnail: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=400&q=80',
    status: 'active',
    rating: 4.7,
    reviewsCount: 320,
  },
];

export const INITIAL_BANNERS: Banner[] = [
  // ── HERO SLIDESHOW BANNERS ──
  {
    id: 'ban-main',
    placement: 'hero',
    title: 'Your Daily Essentials, Delivered Fast.',
    subtitle: 'Farm-fresh vegetables, dairy, atta, snacks, and daily groceries sourced directly from local kiranas and certified suppliers.',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=800&q=80',
    redirectUrl: '/category/fruits-vegetables',
    active: true,
    tag: '10-15 MINS EXPRESS DELIVERY',
    buttonText: 'SHOP NOW',
    badge: '100% FRESH & NATURAL',
    displayOrder: 1,
  },
  {
    id: 'ban-dairy',
    placement: 'hero',
    title: 'Fresh Dairy & Breakfast Restock',
    subtitle: 'Pure Gokul & Amul Milk, Artisanal Breads, Farm-Fresh Eggs & Creamy Butter delivered to your doorstep.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1400&q=80',
    redirectUrl: '/category/dairy-breakfast',
    active: true,
    tag: 'UP TO 40% OFF ON DAIRY',
    buttonText: 'SHOP NOW',
    badge: 'FRESH MORNING RESTOCK',
    displayOrder: 2,
  },
  {
    id: 'ban-snacks',
    placement: 'hero',
    title: 'Crunchy Snacks & Ice-Cold Beverages',
    subtitle: 'Chips, gourmet popcorn, refreshing sodas, juices & tea-time snacks delivered in minutes.',
    image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=1400&q=80',
    redirectUrl: '/category/snacks-munchies',
    active: true,
    tag: 'INSTANT CRAVING DELIVERED',
    buttonText: 'SHOP NOW',
    badge: 'PARTY SNACKS',
    displayOrder: 3,
  },

  // ── MID PROMOTIONAL DUAL BANNERS (Admin Configurable) ──
  {
    id: 'promo-fruits-staples',
    placement: 'promo_dual',
    title: 'Quality & Freshness Guaranteed',
    subtitle: 'Freshly picked seasonal fruits and daily staples sourced from certified farms.',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
    redirectUrl: '/category/fruits-vegetables',
    active: true,
    tag: '100% NATURAL',
    buttonText: 'SHOP NOW',
    badge: '100% NATURAL',
    bgColor: 'from-[#FFF8E7] via-[#FFF3D6] to-[#FFE7B3]',
    badgeBg: 'bg-[#E65100]',
    displayOrder: 1,
  },
  {
    id: 'promo-veg-essentials',
    placement: 'promo_dual',
    title: 'Fresh Vegetables & Cooking Essentials',
    subtitle: 'Crisp greens, potatoes, onions and tomatoes delivered at wholesale rates.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    redirectUrl: '/category/fruits-vegetables?sub=sub-vegetables',
    active: true,
    tag: 'FARM DIRECT',
    buttonText: 'SHOP NOW',
    badge: 'FARM DIRECT',
    bgColor: 'from-[#EBF6EE] via-[#E1F3E7] to-[#D4EDE0]',
    badgeBg: 'bg-[#0B8F5A]',
    displayOrder: 2,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'SAVE20',
    type: 'fixed',
    value: 20,
    minimumOrder: 100,
    maxDiscount: 20,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    usageLimit: 1000,
    active: true,
  },
  {
    id: 'coup-2',
    code: 'POCKET100',
    type: 'fixed',
    value: 100,
    minimumOrder: 499,
    maxDiscount: 100,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    usageLimit: 500,
    active: true,
  },
];

export const DEFAULT_PRICING_RULES: PartnerPricingRules = {
  baseFee: 25,
  perKmRate: 5,
  peakHoursBonus: 10,
  rainSurgeBonus: 15,
  extraOrderBonus: 5,
};

export const INITIAL_DELIVERY_PARTNERS: DeliveryPartner[] = [
  {
    id: 'partner-1',
    userId: 'usr-del-1',
    name: 'Aniket Yadav',
    phone: '+91 9112009988',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    vehicleType: 'EV Scooter (Ather 450X)',
    vehicleNumber: 'MH 14 EV 2026',
    licenseNumber: 'DL-MH-2024-001234',
    verificationStatus: 'verified',
    currentStatus: 'online',
    activeDeliveryStage: 'ARRIVED_AT_STORE',
    activeOrderId: 'PK10245',
    rating: 4.8,
    walletBalance: 2860,
    todayEarnings: 540,
    weekEarnings: 2860,
    monthEarnings: 12840,
    completedDeliveries: 184,
    upiId: 'aniket@oksbi',
    bankAccount: {
      accountNumber: '•••• •••• 4892',
      ifsc: 'SBIN0001244',
      bankName: 'State Bank of India',
    },
    currentLocation: {
      latitude: 19.0232,
      longitude: 73.3218,
      lastUpdated: new Date().toISOString(),
      speed: 24,
    },
    statistics: {
      deliveriesToday: 12,
      deliveriesThisMonth: 184,
      acceptanceRate: 96,
      completionRate: 98,
      onTimeRate: 94,
      customerRating: 4.8,
      hoursOnlineToday: 5.2,
    },
    documents: [
      {
        id: 'doc-1',
        type: 'aadhaar',
        documentNumber: 'XXXX-XXXX-4821',
        status: 'verified',
        submittedAt: '2026-01-10T10:00:00.000Z',
      },
      {
        id: 'doc-2',
        type: 'driving_license',
        documentNumber: 'DL-MH-2024-001234',
        status: 'verified',
        submittedAt: '2026-01-10T10:00:00.000Z',
      },
      {
        id: 'doc-3',
        type: 'vehicle_rc',
        documentNumber: 'MH-14-EV-2026',
        status: 'verified',
        submittedAt: '2026-01-10T10:00:00.000Z',
      },
      {
        id: 'doc-4',
        type: 'bank_passbook',
        documentNumber: 'SBIN0001244',
        status: 'verified',
        submittedAt: '2026-01-10T10:00:00.000Z',
      },
    ],
  },
  {
    id: 'partner-2',
    userId: 'usr-del-2',
    name: 'Sunil Kumar',
    phone: '+91 9820011223',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    vehicleType: 'Hero Splendor Plus',
    vehicleNumber: 'MH 14 BK 4092',
    licenseNumber: 'DL-MH-2023-009876',
    verificationStatus: 'verified',
    currentStatus: 'online',
    rating: 4.9,
    walletBalance: 1450,
    todayEarnings: 420,
    weekEarnings: 2150,
    monthEarnings: 10400,
    completedDeliveries: 142,
    upiId: 'sunil@okhdfcbank',
    currentLocation: {
      latitude: 19.0245,
      longitude: 73.3235,
      lastUpdated: new Date().toISOString(),
      speed: 0,
    },
    statistics: {
      deliveriesToday: 8,
      deliveriesThisMonth: 142,
      acceptanceRate: 98,
      completionRate: 99,
      onTimeRate: 96,
      customerRating: 4.9,
      hoursOnlineToday: 4.0,
    },
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-home',
    userId: 'usr-cust-1',
    addressType: 'Home',
    fullName: 'Aniket Yadav',
    phone: '911200XXXX',
    addressLine1: 'Matoshree Nagar',
    addressLine2: 'Neral, Raigad',
    city: 'Neral',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '410101',
    latitude: 19.033,
    longitude: 73.317,
    isDefault: true,
  },
  {
    id: 'addr-office',
    userId: 'usr-cust-1',
    addressType: 'Office',
    fullName: 'Aniket Yadav',
    phone: '911200XXXX',
    addressLine1: 'Neral MIDC',
    addressLine2: 'Raigad',
    city: 'Neral',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '410101',
    latitude: 19.035,
    longitude: 73.319,
    isDefault: false,
  },
  {
    id: 'addr-parents',
    userId: 'usr-cust-1',
    addressType: 'Parents Home',
    fullName: 'Aniket Yadav',
    phone: '911200XXXX',
    addressLine1: 'Neral MIDC',
    addressLine2: 'Raigad',
    city: 'Neral',
    state: 'Maharashtra',
    country: 'India',
    postalCode: '410101',
    latitude: 19.036,
    longitude: 73.320,
    isDefault: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'PK10245',
    orderNumber: 'PK10245',
    customerId: 'usr-cust-rahul',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 9820011223',
    storeId: 'store-1',
    storeName: 'PocketKirana Central Store',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    subtotal: 684,
    discount: 0,
    deliveryCharge: 0,
    tax: 0,
    total: 684,
    paymentMethod: 'upi',
    paymentStatus: 'completed',
    orderStatus: 'placed',
    placedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    deliverySlot: 'Express (10-15 mins)',
    deliveryOtp: '7412',
    partnerId: undefined,
    partnerName: undefined,
    items: [
      {
        id: 'oi-r1',
        orderId: 'PK10245',
        productId: 'p-milk-fresh-1l',
        product: INITIAL_PRODUCTS[0],
        quantity: 2,
        unitPrice: 62,
        totalPrice: 124,
      },
      {
        id: 'oi-r2',
        orderId: 'PK10245',
        productId: 'p-atta-5kg',
        product: INITIAL_PRODUCTS[17],
        quantity: 1,
        unitPrice: 265,
        totalPrice: 265,
      },
      {
        id: 'oi-r3',
        orderId: 'PK10245',
        productId: 'p-apple-1kg',
        product: INITIAL_PRODUCTS[5],
        quantity: 2,
        unitPrice: 147.5,
        totalPrice: 295,
      },
    ],
  },
  {
    id: 'PK10240',
    orderNumber: 'PK10240',
    customerId: 'usr-cust-priya',
    customerName: 'Priya Verma',
    customerPhone: '+91 9811002233',
    storeId: 'store-1',
    storeName: 'PocketKirana Central Store',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    subtotal: 520,
    discount: 0,
    deliveryCharge: 0,
    tax: 0,
    total: 520,
    paymentMethod: 'upi',
    paymentStatus: 'completed',
    orderStatus: 'preparing',
    placedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    deliverySlot: 'Standard Express',
    deliveryOtp: '9834',
    partnerId: 'partner-1',
    partnerName: 'Sunil Kumar',
    partnerPhone: '+91 9112009988',
    items: [
      {
        id: 'oi-p1',
        orderId: 'PK10240',
        productId: 'p-atta-5kg',
        product: INITIAL_PRODUCTS[17],
        quantity: 1,
        unitPrice: 265,
        totalPrice: 265,
      },
      {
        id: 'oi-p2',
        orderId: 'PK10240',
        productId: 'p-milk-fresh-1l',
        product: INITIAL_PRODUCTS[0],
        quantity: 2,
        unitPrice: 62,
        totalPrice: 124,
      },
    ],
  },
  {
    id: 'PK102938',
    orderNumber: 'PK102938',
    customerId: 'usr-cust-1',
    customerName: 'Aniket Yadav',
    customerPhone: '911200XXXX',
    storeId: 'store-1',
    storeName: 'PocketKirana Hub - Neral',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    couponCode: 'SAVE20',
    subtotal: 289,
    discount: 20,
    deliveryCharge: 20,
    tax: 20,
    total: 309,
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    orderStatus: 'out_for_delivery',
    placedAt: 'Placed on 15 Jun, 7:45 PM',
    deliverySlot: '20 - 30 minutes',
    deliveryOtp: '4829',
    partnerId: 'partner-1',
    partnerName: 'Sunil Kumar',
    partnerPhone: '+91 9112009988',
    items: [
      {
        id: 'oi-1',
        orderId: 'PK102938',
        productId: 'p-milk-fresh-1l',
        product: INITIAL_PRODUCTS[0],
        quantity: 1,
        unitPrice: 62,
        totalPrice: 62,
      },
      {
        id: 'oi-2',
        orderId: 'PK102938',
        productId: 'p-bread-britannia-400g',
        product: INITIAL_PRODUCTS[16],
        quantity: 1,
        unitPrice: 45,
        totalPrice: 45,
      },
      {
        id: 'oi-3',
        orderId: 'PK102938',
        productId: 'p-apple-1kg',
        product: INITIAL_PRODUCTS[5],
        quantity: 1,
        unitPrice: 120,
        totalPrice: 120,
      },
    ],
  },
  {
    id: 'PK102880',
    orderNumber: 'PK102880',
    customerId: 'usr-cust-1',
    customerName: 'Aniket Yadav',
    customerPhone: '911200XXXX',
    storeId: 'store-1',
    storeName: 'PocketKirana Hub - Neral',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    subtotal: 620,
    discount: 0,
    deliveryCharge: 0,
    tax: 0,
    total: 620,
    paymentMethod: 'upi',
    paymentStatus: 'completed',
    orderStatus: 'delivered',
    placedAt: 'Yesterday, 4:20 PM',
    deliverySlot: 'Delivered on 12 Jun',
    deliveryOtp: '1234',
    partnerId: 'partner-1',
    partnerName: 'Sunil Kumar',
    partnerPhone: '+91 9112009988',
    items: [
      {
        id: 'oi-10',
        orderId: 'PK102880',
        productId: 'p-atta-5kg',
        product: INITIAL_PRODUCTS[17],
        quantity: 1,
        unitPrice: 265,
        totalPrice: 265,
      },
    ],
  },
  {
    id: 'PK102750',
    orderNumber: 'PK102750',
    customerId: 'usr-cust-1',
    customerName: 'Aniket Yadav',
    customerPhone: '911200XXXX',
    storeId: 'store-1',
    storeName: 'PocketKirana Hub - Neral',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    subtotal: 180,
    discount: 0,
    deliveryCharge: 0,
    tax: 0,
    total: 180,
    paymentMethod: 'cod',
    paymentStatus: 'completed',
    orderStatus: 'delivered',
    placedAt: '09 Jun, 2:30 PM',
    deliverySlot: 'Delivered on 09 Jun',
    deliveryOtp: '5678',
    partnerId: 'partner-1',
    partnerName: 'Sunil Kumar',
    partnerPhone: '+91 9112009988',
    items: [],
  },
  {
    id: 'PK102600',
    orderNumber: 'PK102600',
    customerId: 'usr-cust-1',
    customerName: 'Aniket Yadav',
    customerPhone: '911200XXXX',
    storeId: 'store-1',
    storeName: 'PocketKirana Hub - Neral',
    addressId: 'addr-home',
    address: INITIAL_ADDRESSES[0],
    subtotal: 450,
    discount: 0,
    deliveryCharge: 0,
    tax: 0,
    total: 450,
    paymentMethod: 'card',
    paymentStatus: 'refunded',
    orderStatus: 'cancelled',
    placedAt: '05 Jun, 11:15 AM',
    deliverySlot: 'Cancelled on 05 Jun',
    deliveryOtp: '0000',
    partnerId: 'partner-1',
    partnerName: 'Sunil Kumar',
    partnerPhone: '+91 9112009988',
    items: [],
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  // CUSTOMER NOTIFICATIONS
  {
    id: 'notif-cust-1',
    recipientId: 'usr-cust-1',
    recipientType: 'customer',
    type: 'ORDER_CONFIRMED',
    category: 'order',
    title: '🛒 Order Confirmed',
    message: 'Your PocketKirana order #PK10245 has been confirmed and is being packed.',
    orderId: 'PK10245',
    deepLink: '/profile?tab=my_orders&orderId=PK10245',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-cust-2',
    recipientId: 'usr-cust-1',
    recipientType: 'customer',
    type: 'OUT_FOR_DELIVERY',
    category: 'delivery',
    title: '🚴 Out for Delivery',
    message: 'Your order #PK102938 is on the way! Sunil Kumar is delivering your items.',
    orderId: 'PK102938',
    deepLink: '/profile?tab=my_orders&orderId=PK102938',
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-cust-3',
    recipientId: 'usr-cust-1',
    recipientType: 'customer',
    type: 'OFFER_DISCOUNT',
    category: 'offer',
    title: '🎉 20% OFF Special Offer',
    message: 'Get 20% OFF on groceries above ₹499. Use code: GROCERY20. Valid today only!',
    couponCode: 'GROCERY20',
    deepLink: '/offers',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-cust-4',
    recipientId: 'usr-cust-1',
    recipientType: 'customer',
    type: 'NEW_PRODUCT',
    category: 'offer',
    title: '🥦 Fresh Organic Harvest',
    message: 'Farm fresh organic vegetables and seasonal fruits now available in your area.',
    deepLink: '/category/fruits-vegetables',
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },

  // ADMIN NOTIFICATIONS
  {
    id: 'notif-admin-1',
    recipientId: 'admin',
    recipientType: 'admin',
    type: 'ADMIN_NEW_ORDER',
    category: 'order',
    title: '🔔 New Order #PK10245',
    message: 'Customer: Rahul • Amount: ₹684 • 3 items • Delivery: 2.4 km',
    orderId: 'PK10245',
    deepLink: '/admin?tab=orders&orderId=PK10245',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    meta: {
      customerName: 'Rahul',
      amount: 684,
      itemsCount: 3,
      distance: '2.4 km',
    },
  },
  {
    id: 'notif-admin-2',
    recipientId: 'admin',
    recipientType: 'admin',
    type: 'ADMIN_LOW_STOCK',
    category: 'inventory',
    title: '⚠️ Low Stock Alert',
    message: 'Tata Salt 1kg only 4 packets remaining. Reorder suggested.',
    deepLink: '/admin?tab=inventory',
    isRead: false,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-admin-3',
    recipientId: 'admin',
    recipientType: 'admin',
    type: 'ADMIN_PARTNER_OFFLINE',
    category: 'system',
    title: '🚴 Delivery Partner Offline',
    message: 'Partner #DP024 (Ramesh Shinde) went offline during peak rush hours.',
    deepLink: '/admin?tab=orders',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-admin-4',
    recipientId: 'admin',
    recipientType: 'admin',
    type: 'ADMIN_PAYMENT_RECEIVED',
    category: 'payment',
    title: '💳 Payment Received',
    message: 'Order #PK10240: ₹520 payment successfully received via Razorpay UPI.',
    orderId: 'PK10240',
    deepLink: '/admin?tab=orders&orderId=PK10240',
    isRead: true,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },

  // DELIVERY PARTNER NOTIFICATIONS
  {
    id: 'notif-dp-1',
    recipientId: 'partner-1',
    recipientType: 'delivery_partner',
    type: 'PARTNER_NEW_DELIVERY',
    category: 'delivery',
    title: '🚴 New Delivery Assigned',
    message: 'Order #PK10245 • Pickup: PocketKirana Hub • Drop: Flat 402, Green Valley • 2.4 km (₹45 payout)',
    orderId: 'PK10245',
    deepLink: '/delivery?orderId=PK10245',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    meta: {
      orderId: 'PK10245',
      amount: 684,
      distance: '2.4 km',
      pickupLocation: 'PocketKirana Hub - Neral',
      deliveryLocation: 'Flat 402, Green Valley',
    },
  },
  {
    id: 'notif-dp-2',
    recipientId: 'partner-1',
    recipientType: 'delivery_partner',
    type: 'PARTNER_PICKUP_READY',
    category: 'delivery',
    title: '📦 Pickup Ready',
    message: 'Order #PK10240 is packed and ready for pickup at store counter.',
    orderId: 'PK10240',
    deepLink: '/delivery?orderId=PK10240',
    isRead: false,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-dp-3',
    recipientId: 'partner-1',
    recipientType: 'delivery_partner',
    type: 'PARTNER_CUSTOMER_NEARBY',
    category: 'delivery',
    title: '📍 Customer Nearby',
    message: 'You are approximately 200m from the delivery location for #PK102938.',
    orderId: 'PK102938',
    deepLink: '/delivery?orderId=PK102938',
    isRead: true,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-dp-4',
    recipientId: 'partner-1',
    recipientType: 'delivery_partner',
    type: 'PARTNER_EARNINGS_CREDITED',
    category: 'delivery',
    title: '💰 Earnings Added',
    message: '₹42 delivery earnings successfully credited to your PocketKirana wallet.',
    deepLink: '/delivery',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
];

// ═══════════════════════════════════════════════════════════════
// 🛒 POCKETKIRANA PICKER & FULFILMENT SEED DATA
// ═══════════════════════════════════════════════════════════════

export const INITIAL_PICKERS: Picker[] = [
  {
    id: 'picker-1',
    name: 'Aniket Yadav',
    phone: '+91 86988 93348',
    email: 'aniket.picker@pocketkirana.com',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    employeeId: 'PKP-014',
    storeId: 'store-1',
    storeName: 'PocketKirana Neral Hub',
    status: 'active',
    currentShift: 'Morning (06:00 - 14:00)',
    joiningDate: '2024-03-15',
    activeTaskId: 'task-pk10245',
    statistics: {
      ordersPickedToday: 15,
      itemsPickedToday: 118,
      averagePickTimeSeconds: 261, // 04:21 min
      accuracyPercent: 99.1,
      missingItemsCount: 3,
      wrongItemsScanned: 1,
      rating: 4.9,
    },
  },
  {
    id: 'picker-2',
    name: 'Ramesh Sawant',
    phone: '+91 98203 45678',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    employeeId: 'PKP-019',
    storeId: 'store-1',
    storeName: 'PocketKirana Neral Hub',
    status: 'active',
    currentShift: 'Evening (14:00 - 22:00)',
    joiningDate: '2024-05-10',
    statistics: {
      ordersPickedToday: 12,
      itemsPickedToday: 94,
      averagePickTimeSeconds: 284,
      accuracyPercent: 98.4,
      missingItemsCount: 2,
      wrongItemsScanned: 2,
      rating: 4.8,
    },
  },
];

export const INITIAL_PICKING_TASKS: PickingTask[] = [
  {
    id: 'task-pk10245',
    orderId: 'PK10245',
    orderNumber: 'PK10245',
    storeId: 'store-1',
    storeName: 'PocketKirana Store - Neral Hub',
    pickerId: 'picker-1',
    pickerName: 'Aniket Yadav',
    status: 'assigned',
    priority: 'HIGH',
    totalItemsCount: 8,
    pickedItemsCount: 0,
    items: [
      {
        id: 'pi-1',
        productId: 'p-tata-salt-1kg',
        productName: 'Tata Salt Vaccum Evaporated',
        sku: 'SALT-TATA-1KG',
        upc: '8901234567890',
        barcode: '8901234567890',
        unit: '1 kg',
        imageUrl: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 2,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[0], // A-01-A-01
        status: 'pending',
        substituteProduct: {
          productId: 'p-aashirvaad-salt-1kg',
          productName: 'Aashirvaad Iodized Salt 1kg',
          price: 29,
          barcode: '8901725181001',
        },
      },
      {
        id: 'pi-2',
        productId: 'p-aashirvaad-atta-5kg',
        productName: 'Aashirvaad Shudh Chakki Atta',
        sku: 'ATTA-AASH-5KG',
        upc: '8901725181222',
        barcode: '8901725181222',
        unit: '5 kg',
        imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[1], // A-01-A-02
        status: 'pending',
      },
      {
        id: 'pi-3',
        productId: 'p-fortune-oil-1l',
        productName: 'Fortune Sunlite Refined Sunflower Oil',
        sku: 'OIL-FORT-1L',
        upc: '8906007280014',
        barcode: '8906007280014',
        unit: '1 L',
        imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[2], // A-02-B-01
        status: 'pending',
      },
      {
        id: 'pi-4',
        productId: 'p-maggi-noodles',
        productName: 'Maggi 2-Minute Masala Noodles',
        sku: 'NODL-MAGG-280G',
        upc: '8901058852445',
        barcode: '8901058852445',
        unit: '280 g',
        imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 2,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[4], // B-01-A-01
        status: 'pending',
      },
      {
        id: 'pi-5',
        productId: 'p-parle-g-800g',
        productName: 'Parle-G Gold Glucose Biscuits',
        sku: 'BISC-PARL-800G',
        upc: '8901719101014',
        barcode: '8901719101014',
        unit: '800 g',
        imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[5], // B-01-B-02
        status: 'pending',
      },
      {
        id: 'pi-6',
        productId: 'p-britannia-bread',
        productName: 'Britannia Daily Fresh White Bread',
        sku: 'BRED-BRIT-400G',
        upc: '8901063012018',
        barcode: '8901063012018',
        unit: '400 g',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[6], // B-02-A-01
        status: 'pending',
      },
      {
        id: 'pi-7',
        productId: 'p-surf-excel-1kg',
        productName: 'Surf Excel Matic Top Load Detergent Powder',
        sku: 'DETG-SURF-1KG',
        upc: '8901030383852',
        barcode: '8901030383852',
        unit: '1 kg',
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[7], // B-03-C-01
        status: 'pending',
      },
      {
        id: 'pi-8',
        productId: 'p-milk-fresh-1l',
        productName: 'Amul Fresh Milk 1L',
        sku: 'AML-FRSH-1L',
        upc: '8901262010015',
        barcode: '8901262010015',
        unit: '1 L',
        imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 0,
        storageLocation: INITIAL_STORAGE_LOCATIONS[9], // C-01-A-01 (Chilled)
        status: 'pending',
      },
    ],
    bagsCount: 2,
    bagTypes: ['Grocery Ambient', 'Cold & Fragile'],
    handoverQrCode: 'PK-HO-PK10245-DP102',
    assignedPartnerId: 'partner-1',
    assignedPartnerName: 'Sunil Kumar (Express Agent)',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-pk10240',
    orderId: 'PK10240',
    orderNumber: 'PK10240',
    storeId: 'store-1',
    storeName: 'PocketKirana Store - Neral Hub',
    pickerId: 'picker-1',
    pickerName: 'Aniket Yadav',
    status: 'packed',
    priority: 'NORMAL',
    totalItemsCount: 3,
    pickedItemsCount: 3,
    items: [
      {
        id: 'pi-11',
        productId: 'p-tata-salt-1kg',
        productName: 'Tata Salt Vaccum Evaporated',
        sku: 'SALT-TATA-1KG',
        upc: '8901234567890',
        barcode: '8901234567890',
        unit: '1 kg',
        imageUrl: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 1,
        quantityPicked: 1,
        storageLocation: INITIAL_STORAGE_LOCATIONS[0],
        status: 'picked',
      },
      {
        id: 'pi-12',
        productId: 'p-maggi-noodles',
        productName: 'Maggi 2-Minute Masala Noodles',
        sku: 'NODL-MAGG-280G',
        upc: '8901058852445',
        barcode: '8901058852445',
        unit: '280 g',
        imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=300&q=80',
        quantityRequired: 2,
        quantityPicked: 2,
        storageLocation: INITIAL_STORAGE_LOCATIONS[4],
        status: 'picked',
      },
    ],
    bagsCount: 1,
    bagTypes: ['Grocery Ambient'],
    handoverQrCode: 'PK-HO-PK10240-DP102',
    assignedPartnerId: 'partner-1',
    assignedPartnerName: 'Sunil Kumar (Express Agent)',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_INVENTORY_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov-100245',
    productId: 'p-tata-salt-1kg',
    productName: 'Tata Salt Vaccum Evaporated 1kg',
    sku: 'SALT-TATA-1KG',
    barcode: '8901234567890',
    type: 'PUTAWAY',
    quantity: 50,
    pickerId: 'picker-1',
    pickerName: 'Aniket Yadav',
    toLocation: 'A-02-B-04',
    reason: 'Stock Inward PO #PO-9912',
    timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'mov-100244',
    productId: 'p-milk-fresh-1l',
    productName: 'Amul Fresh Milk 1L',
    sku: 'AML-FRSH-1L',
    barcode: '8901262010015',
    type: 'PICK',
    quantity: -2,
    orderId: 'PK10240',
    orderNumber: 'PK10240',
    pickerId: 'picker-1',
    pickerName: 'Aniket Yadav',
    fromLocation: 'C-01-A-01',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'mov-100243',
    productId: 'p-fortune-oil-1l',
    productName: 'Fortune Sunlite Oil 1L',
    sku: 'OIL-FORT-1L',
    barcode: '8906007280014',
    type: 'ADJUSTMENT',
    quantity: -1,
    pickerId: 'picker-1',
    pickerName: 'Aniket Yadav',
    fromLocation: 'A-02-B-01',
    reason: 'Damaged Seal Reported',
    timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
];




