export interface Recipe {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  image: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
  categorySlug: string;
  tags: string[];
  ingredients: { item: string; qty: string; productSlug?: string }[];
  steps: string[];
  tip?: string;
}

export const RECIPES: Recipe[] = [
  {
    id: 'r-1',
    slug: 'soft-wheat-roti',
    title: 'Soft Wheat Roti',
    subtitle: 'Classic Indian flatbread — perfect with any sabzi',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    difficulty: 'Easy',
    category: 'Breakfast & Meals',
    categorySlug: 'breakfast-meals',
    tags: ['roti', 'flatbread', 'vegetarian', 'quick'],
    ingredients: [
      { item: 'Aashirvaad Whole Wheat Atta', qty: '2 cups', productSlug: 'aashirvaad-shuddh-chakki-atta-5kg' },
      { item: 'Water', qty: '¾ cup (warm)' },
      { item: 'Salt', qty: '½ tsp' },
      { item: 'Amul Butter (for serving)', qty: '1 tsp per roti', productSlug: 'amul-pasteurized-salted-butter' },
    ],
    steps: [
      'In a large bowl, mix atta and salt. Gradually add warm water and knead into a soft, smooth dough.',
      'Rest the dough for 15 minutes covered with a damp cloth.',
      'Divide into equal balls. Roll each ball into a thin circle (6-7 inch diameter).',
      'Heat a tawa over medium-high heat. Cook each roti for 30 seconds per side until brown spots appear.',
      'Apply butter immediately and serve hot.',
    ],
    tip: 'Adding a teaspoon of ghee to the dough makes rotis extra soft and pliable.',
  },
  {
    id: 'r-2',
    slug: 'masala-chai',
    title: 'Classic Masala Chai',
    subtitle: 'Spiced Indian milk tea — perfect morning ritual',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    prepTime: '2 min',
    cookTime: '8 min',
    servings: 2,
    difficulty: 'Easy',
    category: 'Beverages',
    categorySlug: 'beverages',
    tags: ['chai', 'tea', 'milk', 'spiced', 'morning'],
    ingredients: [
      { item: 'Water', qty: '1 cup' },
      { item: 'Amul Taaza Milk', qty: '1 cup', productSlug: 'amul-taaza-toned-fresh-milk' },
      { item: 'Tea leaves (CTC)', qty: '1.5 tsp' },
      { item: 'Sugar', qty: '2 tsp (to taste)' },
      { item: 'Ginger', qty: '½ inch, crushed' },
      { item: 'Cardamom pods', qty: '2, crushed' },
    ],
    steps: [
      'Bring 1 cup water to a boil in a saucepan.',
      'Add crushed ginger and cardamom. Boil for 1 minute.',
      'Add tea leaves and boil for 1 more minute.',
      'Pour in milk and sugar. Bring to a boil.',
      'Simmer for 2–3 minutes until the tea is well blended and aromatic.',
      'Strain into cups and serve hot.',
    ],
    tip: 'For extra richness, use full cream Amul Gold milk.',
  },
  {
    id: 'r-3',
    slug: 'banana-smoothie',
    title: 'Creamy Banana Smoothie',
    subtitle: 'Quick, nutritious and naturally sweet',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 2,
    difficulty: 'Easy',
    category: 'Smoothies & Drinks',
    categorySlug: 'smoothies',
    tags: ['banana', 'smoothie', 'healthy', 'breakfast', 'no-cook'],
    ingredients: [
      { item: 'Robusta Golden Bananas', qty: '2 ripe', productSlug: 'robusta-golden-bananas' },
      { item: 'Amul Masti Dahi', qty: '½ cup', productSlug: 'amul-masti-dahi-pouch-400g' },
      { item: 'Amul Gold Milk', qty: '1 cup', productSlug: 'amul-gold-full-cream-milk' },
      { item: 'Honey', qty: '1 tsp' },
      { item: 'Ice cubes', qty: '4–6' },
    ],
    steps: [
      'Peel and slice the bananas.',
      'Add bananas, dahi, milk, and honey to a blender.',
      'Add ice cubes.',
      'Blend until smooth and creamy.',
      'Pour into glasses and serve immediately.',
    ],
    tip: 'For a thicker smoothie, freeze the bananas the night before.',
  },
  {
    id: 'r-4',
    slug: 'quick-tomato-sabzi',
    title: 'Quick Tomato Sabzi',
    subtitle: 'A 10-minute side dish with everyday ingredients',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '10 min',
    servings: 2,
    difficulty: 'Easy',
    category: 'Quick Meals',
    categorySlug: 'quick-meals',
    tags: ['tomato', 'sabzi', 'vegetarian', 'quick', 'Indian'],
    ingredients: [
      { item: 'Farm Fresh Tomatoes', qty: '4 medium', productSlug: 'farm-fresh-hybrid-tomatoes' },
      { item: 'Onion', qty: '1 medium, chopped', productSlug: 'fresh-nashik-red-onions' },
      { item: 'Mustard oil', qty: '2 tbsp' },
      { item: 'Cumin seeds', qty: '½ tsp' },
      { item: 'Turmeric powder', qty: '¼ tsp' },
      { item: 'Red chilli powder', qty: '½ tsp' },
      { item: 'Coriander leaves', qty: 'for garnish' },
      { item: 'Salt', qty: 'to taste' },
    ],
    steps: [
      'Heat oil in a pan. Add cumin seeds and let them splutter.',
      'Add chopped onion and sauté until golden.',
      'Add chopped tomatoes, turmeric, chilli powder, and salt.',
      'Cook on medium heat for 8–10 minutes, stirring occasionally, until tomatoes break down.',
      'Garnish with fresh coriander and serve with roti or rice.',
    ],
    tip: 'Add a pinch of sugar to balance the sourness of tomatoes.',
  },
  {
    id: 'r-5',
    slug: 'egg-bhurji',
    title: 'Spicy Egg Bhurji',
    subtitle: 'Indian-style scrambled eggs — breakfast or anytime snack',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '8 min',
    servings: 2,
    difficulty: 'Easy',
    category: 'Breakfast & Meals',
    categorySlug: 'breakfast-meals',
    tags: ['eggs', 'breakfast', 'quick', 'protein'],
    ingredients: [
      { item: 'Farm Fresh Eggs', qty: '4 eggs', productSlug: 'farm-fresh-white-eggs-tray-6' },
      { item: 'Onion', qty: '1 medium, finely chopped', productSlug: 'fresh-nashik-red-onions' },
      { item: 'Tomato', qty: '1 medium, chopped', productSlug: 'farm-fresh-hybrid-tomatoes' },
      { item: 'Amul Butter', qty: '1 tbsp', productSlug: 'amul-pasteurized-salted-butter' },
      { item: 'Green chillies', qty: '1–2, chopped' },
      { item: 'Cumin seeds', qty: '½ tsp' },
      { item: 'Salt & pepper', qty: 'to taste' },
    ],
    steps: [
      'Melt butter in a pan over medium heat. Add cumin seeds.',
      'Add onion and green chillies. Sauté until softened.',
      'Add tomatoes and cook for 2 minutes.',
      'Beat eggs with salt and pepper. Pour into the pan.',
      'Stir continuously with a spatula until eggs are softly scrambled.',
      'Serve hot with buttered bread or roti.',
    ],
  },
  {
    id: 'r-6',
    slug: 'cold-lemon-drink',
    title: 'Homemade Nimbu Pani',
    subtitle: 'Classic Indian lemonade — beat the heat naturally',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 4,
    difficulty: 'Easy',
    category: 'Beverages',
    categorySlug: 'beverages',
    tags: ['lemonade', 'refreshing', 'summer', 'no-cook'],
    ingredients: [
      { item: 'Fresh lemons', qty: '3 (juiced)' },
      { item: 'Water', qty: '4 cups (chilled)' },
      { item: 'Sugar', qty: '3–4 tbsp (to taste)' },
      { item: 'Black salt', qty: '¼ tsp' },
      { item: 'Roasted cumin powder', qty: '¼ tsp' },
      { item: 'Mint leaves & ice', qty: 'for serving' },
    ],
    steps: [
      'Squeeze juice from 3 lemons into a pitcher.',
      'Add sugar and stir until dissolved.',
      'Add 4 cups chilled water, black salt, and cumin powder.',
      'Mix well and taste — adjust sweetness and tanginess.',
      'Pour over ice, garnish with mint leaves, and serve immediately.',
    ],
    tip: 'Replace sugar with jaggery powder for a healthier, earthier version.',
  },
];
