'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAppStore } from '@/lib/store';
import { QrCode, Bike, ArrowRight, ShieldCheck, Phone, Sparkles } from 'lucide-react';
import { showToast } from '@/components/ui/Toast';

export default function DeliveryLoginPage() {
  const router = useRouter();
  const { validateAndLoginPartnerQR, loginPartnerByPhoneOrCode, deliveryPartners } = useAppStore();

  const [loginMode, setLoginMode] = useState<'QR' | 'PHONE'>('QR');
  const [qrInput, setQrInput] = useState('');
  const [phoneOrCode, setPhoneOrCode] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleQrLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!qrInput.trim()) {
      showToast('Please scan or enter your Admin Login QR token', 'error');
      return;
    }

    setIsLoading(true);
    const res = validateAndLoginPartnerQR(qrInput);
    setIsLoading(false);

    if (res.success) {
      showToast(res.message, 'success');
      router.replace('/home');
    } else {
      showToast(res.message, 'error');
    }
  };

  const handlePhoneLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!phoneOrCode.trim()) {
      showToast('Please enter your Phone or Partner Code', 'error');
      return;
    }

    setIsLoading(true);
    const res = loginPartnerByPhoneOrCode(phoneOrCode);
    setIsLoading(false);

    if (res.success) {
      showToast(res.message, 'success');
      router.replace('/home');
    } else {
      showToast(res.message, 'error');
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col justify-between p-6 font-sans">
      
      {/* Top Brand Hero */}
      <div className="pt-10 text-center space-y-4 max-w-sm mx-auto">
        <div className="w-20 h-20 rounded-3xl bg-emerald-600 text-white flex items-center justify-center mx-auto shadow-xl shadow-emerald-600/30">
          <Bike className="w-10 h-10" />
        </div>
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight">Pocket Kirana Delivery</h1>
          <span className="text-xs text-emerald-800 font-bold uppercase tracking-wider block mt-1">
            Delivery Partner App
          </span>
        </div>
      </div>

      {/* Login Card */}
      <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-md max-w-sm mx-auto w-full space-y-5">
        
        {/* Mode Selector */}
        <div className="flex bg-slate-100 p-1 rounded-2xl">
          <button
            type="button"
            onClick={() => setLoginMode('QR')}
            className={`flex-1 py-2 text-xs font-black rounded-xl transition-all cursor-pointer ${
              loginMode === 'QR' ? 'bg-white text-emerald-800 shadow-xs' : 'text-slate-500'
            }`}
          >
            Admin QR Code
          </button>
          <button
            type="button"
            onClick={() => setLoginMode('PHONE')}
            className={`flex-1 py-2 text-xs font-black rounded-xl transition-all cursor-pointer ${
              loginMode === 'PHONE' ? 'bg-white text-emerald-800 shadow-xs' : 'text-slate-500'
            }`}
          >
            Phone / Partner Code
          </button>
        </div>

        {loginMode === 'QR' ? (
          <form onSubmit={handleQrLogin} className="space-y-4 animate-in fade-in">
            <div className="bg-emerald-50 border border-emerald-200 p-3.5 rounded-2xl text-xs space-y-1">
              <strong className="text-emerald-950 font-black block">Admin Secure QR Login</strong>
              <p className="text-emerald-800 text-[11px]">
                Scan the unique authorization QR generated by your Store Admin from the Dashboard.
              </p>
            </div>

            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-700 mb-1.5">
                Admin Token / QR Value
              </label>
              <input
                type="text"
                placeholder="e.g. PK-DP-AUTH-ABCD1234"
                value={qrInput}
                onChange={(e) => setQrInput(e.target.value.toUpperCase())}
                autoFocus
                required
                className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-3 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:border-emerald-600 uppercase"
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 active:scale-95 text-white font-black text-xs rounded-2xl shadow-lg shadow-emerald-600/30 flex items-center justify-center gap-2 transition-transform cursor-pointer uppercase tracking-wider"
            >
              <QrCode className="w-4 h-4" />
              <span>{isLoading ? 'AUTHENTICATING...' : 'AUTHENTICATE QR'}</span>
            </button>
          </form>
        ) : (
          <form onSubmit={handlePhoneLogin} className="space-y-4 animate-in fade-in">
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-700 mb-1.5">
                Registered Mobile or Partner ID
              </label>
              <input
                type="text"
                placeholder="e.g. 8698893348 or DP001"
                value={phoneOrCode}
                onChange={(e) => setPhoneOrCode(e.target.value)}
                autoFocus
                required
                className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-3 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:border-emerald-600"
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 active:scale-95 text-white font-black text-xs rounded-2xl shadow-lg shadow-emerald-600/30 flex items-center justify-center gap-2 transition-transform cursor-pointer uppercase tracking-wider"
            >
              <ShieldCheck className="w-4 h-4" />
              <span>{isLoading ? 'SIGNING IN...' : 'SIGN IN TO SHIFT'}</span>
            </button>
          </form>
        )}

      </div>

      <div className="text-center text-[11px] text-slate-400 font-mono pb-4">
        Pocket Kirana Delivery Workspace • v1.0.0 (Android)
      </div>

    </div>
  );
}
